herbie-fp/herbie

- herbie/config.rkt
- herbie/interface/interact.rkt
- herbie/main.rkt
- herbie/plot.rkt
- herbie/points.rkt
- herbie/reports/datafile.rkt
- herbie/reports/graph.js
- herbie/reports/make-index.rkt
- herbie/reports/make-report.rkt
Fix the single-precision mode to work.
+ The single-precision is reflected in the graphs and plots we draw.
+ Removed the `sample:double` flag; `precision:double` changes the meaning of the `default` sampler.
+ Modified the new main loop to use the flags that control the main loop.
> Fix single precision

- herbie/reports/thread-pool.rkt
The thread pool no longer has a manager thread, which makes the flow a little simpler and shortens the code. It should also reduce memory usage a bit.
> Fix thread pool

- bench/libraries/jmatjs.rkt
- bench/libraries/mathjs/arithmetic.rkt
When these are written in filenames, it can confuse make when it tries to
compile the extracted C code.
> Remove "<" and ">" from some bench names

- Makefile
- herbie/compile/overhead.mk
As documented in the MPFR manual, the correct order is -lmpfr -lgmp (if -lgmp is used first, GMP symbols not used directly by the program may be removed before the linker can detect that they are needed by MPFR).
> Use -lgmp after -lmpfr

- herbie/distributions.rkt
- herbie/infer-regimes.rkt
- herbie/interface/interact.rkt
- herbie/main.rkt
- herbie/points.rkt
- herbie/test.rkt
This pulls point sampling into a new file, `distributions.rkt`, removing the parser code from `test.rkt` and the sampler code from `points.rkt`. The sampler API is also extended to allow returning `#f` to indicate that no point could be sampled and that the caller should try again, allowing for pre-conditions in future versions.
To improve modularity, sampling functions are not longer exposed, only the `eval-sampler` parser function. We should move to limit the callers of this function in the future.
> Reform sampler syntax

- .gitignore
- LICENSE.md
- herbie/compile/results-to-csv.rkt
- herbie/info.rkt
- herbie/interface/inout.rkt
This change allows Herbie to be installed as a Racket package, and provides the Herbie command line tool as a raco command. This uses the `herbie/interface/inout.rkt` entrypoint, rather than the report generation entrypoint. As far as I'm aware, that's the intended future main entrypoint once the CLI is cleaned up. Let me know if I should change it. The following small changes are included:
1. Changes the `#:args` from _ to () to declare no args are accepted,
rather than all args are ignored. Improves the command help output
2. Adds `compiled/` to the git ignore, which is the directory created by
DrRacket for zo files
Additionally, this change adds a notice to the license file indicating the copyright to my
patch is owned by Google (wrote this on corp laptop). This does not
change the …
> Add package info and raco command information

- .travis.yml
- herbie/info.rkt
- Parallelizes travis over various racket versions to determine
herbie’s version support
- Installs racket via Greg Hendershott’s installation script to handle
installation of multiple versions
- Adds racket’s bin dir to `PATH` to allow referring to `racket` and
`raco` commands directly
- Changes installation from directly installing dependencies to
installing herbie as a package and picking up dependencies from its
`info.rkt` file
- Moves installation from `before_install` to `install`.
> Expand travis script

- .travis.yml
- herbie/herbie.rkt
- Changes Travis to use the new `herbie.rkt` command line interface
- Adds support for explicitly requesting a random seed using the
`--seed` flag
- Specifies the exact seed used (using the seed from build #357.2 since
it was known to work) and adds an additional build job using a random
seed that’s allowed to fail.
> Use herbie.rkt in travis with seed

- .travis.yml
The `after_success` phase runs after travis uploads cached directories, making this useless.
> Fix build phase of docker image caching

- www/index.html
In the Index page sample for `sqrt(x + 1) - sqrt(x)`
> Fix typo in example rewriting on index page

- src/syntax/rules.rkt
Not really significant. Just came across this. I don't suppose (or `grep` doesn't suppose) this is referenced anywhere by name.
> Fix typo in ruleset

- .travis.yml
- infra/index.css
- src/config.rkt
- src/errors.rkt
- src/formats/tex.rkt
- src/plot.rkt
- src/reports/common.rkt
- src/reports/graph.css
- src/reports/make-graph.rkt
- src/reports/make-report.rkt
- src/reports/report.css
- src/reports/report.js
Totally reworks the details pages generated by the reports script for every input.
+ Bigger graphs, with tabs for different variables
+ Larger and clearer design
+ More compact derivations
+ Easier reproduction
+ Mark regimes on plot
+ Saner tick marks on plot
+ Nicer error and timeout pages
+ Python-style, not math-style, TeX for `if` statements
This feature is intended for the 1.1 release.
> New details page

- src/core/matcher.rkt
- src/core/reduce.rkt
- src/core/taylor.rkt
- src/function-definitions.rkt
When one function is an alias for simpler functions, such as `(tan x)` for `(/ (sin x) (cos x))`, we normally have rules expanding on this definition. With this change, series expansion can now use those rules for series-expansion automatically.
> Teach series expansion about function definitions

- bench/numerics/fma.fpcore
- infra/index.css
- src/config.rkt
- src/errors.rkt
- src/formats/test.rkt
- src/herbie.rkt
- src/plot.rkt
- src/programs.rkt
- src/reports/make-graph.rkt
- src/reports/make-report.rkt
- src/reports/report.css
- src/reports/rerun.rkt
- src/sandbox.rkt
- src/syntax/rules.rkt
- src/web/demo.rkt
- www/doc/1.1/faq.html
Print error messages for invalid syntax with line and column info, and with more-detailed error messages.
This should make it much easier to fix FPCore syntax bugs. Note that bad parenthisation still triggers a not-too-user-friendly error message, unfortunately.
> Syntax check info

- Dockerfile
This pins the Racket version in Docker to Racket 6.8.
I also removed a line which installed a bunch of packages. @jackfirth, do you know why that line is in there?
> Pin Racket version in Docker

- .travis.yml
- src/core/regimes.rkt
For zero-argument expressions, inferring a split-point just chooses the
best alternative. This is the correctly handled by the rest of the code.
> Support zero-argument expressions

- src/programs.rkt
- src/syntax/syntax.rkt
Operators can list '* as a valid number of arguments (which means any number).
This used to mostly work; then stopped when we added syntax checking; but now works again and furthermore according to FPBench spec.
> Add variary comparators

- src/syntax/syntax.rkt
These were forgotten when the comparison operators were made variary.
> Allow variary AND and OR

- src/formats/test.rkt
- src/range-analysis.rkt
- src/syntax/distributions.rkt
Implement range table to store information about preconditions. A range table contains at most one interval for one variable. This enables earlier failure if the precondition entered by the client is not valid.
> Faster pre sampling

- src/syntax/rules.rkt
This adds some half angle rewrite rules for tangent.
Additionally, there are some tweaks to the rules testing.  It seems that for some implementations of libm (at least on macOS), the unpow2 rule was actually not "fp safe".
> tan half angle rules

- src/core/simplify.rkt
This fixes a subtle but pervasive and pernicious bug in simplification.
Simplification proceeds by estimating a number of iterations (of egraph rewriting) necessary to simplify a term, then doing that many (with a bound on both nodes and iters). The estimated number of iterations is simple: for every binary operator, a commutation and an associativity can be necessary (so 2 iterations) and for other operators we estimate 1. The maximum through any branch should give a nice bound.
The bug in question causes us not to do some rewriting steps on some iterations, even if they are valid. As a result, outputs are often "undersimplified".
The issue is that the simplifier *first* computes the set of valid rewrites, *then* executes them one after another. But one rewrite can invalidate another, …
> Simplify bug

- src/syntax/rules.rkt
This adds a set of rules for tricks from the numerical methods literature.  For now, it only has the difference of products using fmas and is included in numerics group.
> Diff of prods

- src/core/regimes.rkt
Fixes a bug in regimes wherein regimes may attempt to put a branch between two points even if those points evaluate to the same value under the branch expression. The fix is to pass in an array of true/false values that determine where branches are allowed, and not to consider branches where they are not allowed.
Also some new unit tests are added to test that this functionality works. The commit is unlikely to affect the accuracy of Herbie in most cases.
> Teach regimes not to split equal points

- src/common.rkt
- src/config.rkt
- src/float.rkt
- src/programs.rkt
- src/syntax/rules.rkt
- src/syntax/syntax.rkt
This PR adds some basic rules for merging nested conditionals with related rules for simplifying boolean and comparison operators.  To support unit tests, we also added optional type annotations to rule sets (e.g., to sample boolean inputs to the boolean operator rewrites).  Finally, we extended the notion of "ulp difference" to comparing boolean outputs where unequal bools have 64 ulps of error for now.
> Simplify conditions

- bench/libraries/mathjs/arithmetic.fpcore
- src/bigcomplex.rkt
- src/core/enode.rkt
- src/core/matcher.rkt
- src/core/simplify.rkt
- src/core/taylor.rkt
- src/formats/test.rkt
- src/programs.rkt
- src/shell.rkt
- src/syntax/rules.rkt
- src/syntax/syntax.rkt
- src/type-check.rkt
The Herbie core now treats complex and real operations as different functions; the front-end does the renaming necessary to make this transparent for users. For example, `(exp (complex 1 0))` is replaced with `(exp.c (complex 1 0))`.
Doing this meant adding a new table of "parametric" operators, which the front-end will replace, and adding types to rules, to ensure that only valid rewritings were carried out. One benefit is that we are no longer type-checking expressions over and over again in the core of Herbie.
> Split complex and real operators

- src/core/egraph.rkt
- src/core/simplify.rkt
- src/core/taylor.rkt
This PR enables constant simplification, so that the simplifier can turn `(+ 2 2)` into `4` and similar. Constant simplification only happens when the computation produces a Racket `exact?` value, so for example `(+ 2.0 2.0)` would not be computed down to `4.0`. This ensures that no rounding error can be incurred by computation.
This series of commits also adds to unrelated items:
+ A new egraph extraction algorithm
+ New series expansion support for `pow`s
The new egraph extraction algorithm improves on the old one by iteratively improving the extraction of any expression until fixed-point, while the old one improves it until the egraph root has an extraction. The fixedpoint can lead to simpler expressions, but it takes a lot longer, so is currently disabled.
The series expansion support …
> Constant simplification

- src/web/demo.rkt
Allows users to submit expressions to Herbie web from a URL. It works with the standard concurrency and caching mechanisms. This will allow Herbie to be listed on the [FPBench benchmarks page](http://fpbench.org/benchmarks.html)!
> Enable GET-based submissions

- bench/numerics/rump.rkt
- infra/travis.rkt
- src/common.rkt
- src/config.rkt
- src/core/localize.rkt
- src/core/matcher.rkt
- src/core/regimes.rkt
- src/core/taylor.rkt
- src/debug.rkt
- src/errors.rkt
- src/formats/test.rkt
- src/herbie.rkt
- src/mainloop.rkt
- src/points.rkt
- src/programs.rkt
- src/sandbox.rkt
- src/shell.rkt
- src/syntax/rules.rkt
- src/web/common.rkt
- src/web/make-graph.rkt
- src/web/report.css
- src/web/timeline.rkt
The goal of this PR is to make recursive rewriting more powerful. In particular, if RR is trying to rewrite an expression like `(f e1 e2)` to have an `f` at its head, the existing RR algorithm will not allow any changes here, but this PR lifts that restriction. This allows rewriting, for example, `(* (* x x) (* y y))` as `(* (* x y) (* x y))`.
The PR also bundles some unrelated improvements (sorry!):
- A "reset" system to reset all sorts of caches and so on in one step.
- A warnings system, to avoid duplicate warnings and to push warnings into HTML
- Added the program to timeout / traceback pages
> Better recursive rewriting

- infra/travis.rkt
- src/core/egraph.rkt
- src/core/regimes.rkt
- src/core/simplify.rkt
- src/mainloop.rkt
- src/programs.rkt
- src/syntax/syntax.rkt
- src/syntax/types.rkt
This simple changes significantly speeds up Herbie. Every time we are in the simplify phase, we simplify a whole bunch of expressions at once. With this change, we use a single egraph for that: add each expression, iterate the egraph, and then extract the best result for each expression. Since most expressions are similar, the shared egraph saves a significant amount of time.
Initial results seem promising: simplify is 3–6× faster and Herbie as a whole is 1.5–3× faster.
> Batch simplify

- src/config.rkt
- src/core/simplify.rkt
- src/programs.rkt
- src/syntax/rules.rkt
This PR refactors `simplify.rkt` to enforce the node limit after every rule application, instead of just after every iteration. This cures the issue where sometimes Herbie runs out of memory and hard crashes, since that seems to have been due to a runaway egraph explosion.
The PR also substantially decreases the node limit: formally from 2000 to 1000 but in practice significantly more since before this PR the node limit was usually surpassed by 2–5× before it kicked in. The new node limit was chosen by a set of experiments on the `mathematics` and `libraries` suites, which suggested that the decrease would not cost accuracy and would increase performance.
> Faster harder node limit

- src/core/alt-table.rkt
- src/syntax/rules.rkt
Pruning can be quite slow. The easiest way to speed it up is to prune fewer alts, and luckily this is easy because we prune the same program many times: rewriting followed by simplification generates a lot of duplicates. This patch eliminates the duplicates, both within the set of new alts and alts alts that duplicate alts already in the table. Speed-ups on pruning seem to be on the order of 1.5–2×, and overall speed-ups seem to be roughly 10%.
Pruning could likely be made faster yet by avoiding computing the `errors` of each incoming alt multiple times; that error computation is the slowest part of pruning.
> Deduplicate in pruning

- src/biginterval.rkt
This PR switches the interval library from using `math/bigfloat` to using `math/private/bigfloat/mpfr`. This allows us to use the MPFR functions without checking contracts on every call. Since each interval function calls lots of MPFR functions, this is a big win (25% speedup for sampling in some tests, so projected 5–10% speedup to Herbie).
The actual change is just renaming a lot of functions, and the internals of `math/bigfloat` have been pretty stable, so I don't see this as adding much maintenance burden.
> Use the private MPFR library instead of `math/bigfloat` in biginterval

- src/sandbox.rkt
- src/web/make-graph.rkt
Resugaring (replacing specialized functions like `+.p16` with their more general versions) is currently done too early in the pipeline, which leads to some convoluted code later on. This PR changes the state of affairs to move resugaring later. This should also fix some bugs associated with said convoluted code.
> Move resugaring

- src/common.rkt
- src/points.rkt
I moved the guts of the sampling code to `random-ranges` in `common.rkt`, which deals only with integers and is not Herbie-specific. `sample-multi-bounded` now just converts to and from ordinals and uses the intervals data structure.
> Split sample-multi-bounded

- src/common.rkt
- src/core/localize.rkt
- src/core/periodicity.rkt
- src/core/regimes.rkt
- src/float.rkt
- src/formats/test.rkt
- src/mainloop.rkt
- src/points.rkt
- src/programs.rkt
- src/sandbox.rkt
- src/syntax/test-rules.rkt
- src/web/make-graph.rkt
- src/web/timeline.rkt
This PR begins the process of removing the process of checking values for their associated representation, and instead passing the representation through to the necessary functions. This change focuses on `infer-representation` and `infer-double-representation` in `float.rkt` and removes all references to these functions from the file (aside from the definition). Note that these functions are still called by other files; this is just the first step in removing this process from interface code.
> Interface2: Remove representation inference from values in `float.rkt`

- src/biginterval.rkt
- src/formats/datafile.rkt
- src/formats/test.rkt
- src/mainloop.rkt
- src/points.rkt
- src/programs.rkt
- src/sandbox.rkt
- src/syntax-check.rkt
- src/type-check.rkt
- src/web/run.rkt
Adds support for `:spec` and `let*`.
> Support some FPCore 1.2 syntax

- src/web/timeline.rkt
Previously tried to call `infer-representation` with no arguments when trying to pass through the representation for `flval`. This PR simplifies the code and fixes the bug.
> Fixed bug trying to make the timeline

- src/biginterval.rkt
- src/common.rkt
- src/core/alt-table.rkt
- src/core/enode.rkt
- src/core/localize.rkt
- src/core/periodicity.rkt
- src/core/regimes.rkt
- src/float.rkt
- src/formats/test.rkt
- src/formats/tex.rkt
- src/interface.rkt
- src/mainloop.rkt
- src/points.rkt
- src/programs.rkt
- src/sandbox.rkt
- src/syntax/test-rules.rkt
- src/type-check.rkt
- src/web/common.rkt
- src/web/make-graph.rkt
- src/web/timeline.rkt
This PR removes all instances of `infer-representation` and `infer-double-representation` from the code. Rather than looking at values to figure out their representation, we now pass through relevant representation information and set a global variable `*output-prec*` which tracks the output precision for a given FPCore. Note that currently the representation that is passed through only corresponds to the output precision since input FPCores are not yet allowed to have variable precision.
> Interface2: Remove Representation Inference

- src/syntax/rules.rkt
- src/syntax/syntax.rkt
The `erfc-erf` rule would only operate on `(- 1 (erf x))`; that's needlessly specific since we can introduce the subtraction on the right hand side.
> Generalize the erfc-erf rule (for #247)

- src/web/make-graph.rkt
A bug appeared that crashed the web interface whenever a user tried to run in single-precision mode. This was caused when generating the report due to a mix-up between precisions and types, sometimes passing through `real` as the precision when we should have instead been passing through `binary32` or `binary64`. We would then check the flag to see if we were running in double or single precision mode rather than just using the precision that we already had from the test output, and because we are no longer running in the sandbox when the report is generated, we would get the incorrect precision and then try to call the `binary64` version of `repr->ordinal` on `binary32` points. This PR fixes that crash by never passing through precision as the type `real` rather than the actual …
> Fix web bug for single-precision runs

- src/float.rkt
- www/doc/1.3/faq.html
- www/doc/1.4/faq.html
When `value->string` was passed in an exact value, the function would infinite loop. This was because `=-or-nan?` would compare the exact value with the value that had been converted back from a bigfloat to the representation (which for exact values would be labelled as binary64 or binary32) and would then try to compare an inexact value to an exact value. This change will always compare the inexact values and adds in a check to make sure the function doesn't infinite loop in the case that the function can't find a unique string to represent the value.
> Fix bug in value->string causing an infinite loop

- src/syntax/syntax.rkt
This change fixes a bug in the non-ffi fallback operator bug that would cause it to incorrectly pass through complex values. Several built-in racket functions including `log` and `asin` can return complex numbers on certain inputs. This change addresses the issue by wrapping the fallback functions with a `no-complex` function that converts any complex numbers to `+nan.0` during evaluation. This PR address issue #256.
> Fixed non-ffi fallback bug

- src/formats/test.rkt
Previously, if a precision was not specified in the FPCore, then Herbie would assume `binary64` instead of using the `precision:double` flag. This change fixes that bug.
> Use `precision:double` Flag as Fallback Precision

- src/plot.rkt
- src/range-analysis.rkt
Sometimes a precondition eliminates all possible values, like for `(< 2 x 1)`. In that case, Herbie produces the "no valid values" error message. That message mentions a variable; however, when there are multiple variables, it often mentions the wrong one. For example if you have variables `x` and `y`, and the precondition `(< 2 y 1)`, Herbie complains that there are no valid values of `x`. It is technically right, but substantially wrong: nothing is the problem with `x`, though there is something wrong with `y`.
The fix involves the two different ways of representing "no valid values" in the "range-table" structure. One is the range-table `#f`, which mentions no variables (and will raise an error with the first variable in the list). The other is the range-table `#hash([y . ()])`, which …
> Mention the right variable when there are no valid values

- infra/make-index.rkt
- src/core/egraph.rkt
- src/core/ematch.rkt
- src/core/matcher.rkt
- src/core/simplify.rkt
The core issue is with not replacing enough expressions by their representative. In particular, the bug occurs during pattern substitution. In substitution, we might want to substitute into the pattern `(+ a b)` with `a` bound to some enode X and `b` bound to another Y. Before this bug, X and Y were used directly; in the new code, X and Y are first upgraded to their pack leaders. This fixes #255.
The reason this bug has such a large impact is that it creates many "useless" nodes in the e-graph, which are just copies of other nodes but not equal to them.
To reduce future maintenance, I've replaced the `substitute-e` procedure, for substituting e-nodes into a pattern, with the regular `pattern-substitute` procedure, which handles the e-nodes fine, plus `mk-enode-rec!` to create the final …
> Fix an old simplify bug

- src/core/simplify.rkt
- src/mainloop.rkt
- src/sandbox.rkt
The final simplify step is supposed to do only transformations that are provably valid in the floating-point numbers, to avoid showing users junk. However, it currently also applies precomputation, which in a few cases causes the result to be less accurate. (Because more-exact value in one part of the program may make the overall program less accurate.) Avoiding precomputation in final simplify seems like the right move.
This PR removes `one-iter` in `simplify.rkt`, replacing it was an abstraction called "phases". Each rewrite rule is a phase, as is precomputation and pruning. Each phase can also be turned on or off by command line flags.
> No precompute in final simplify

- src/formats/datafile.rkt
- src/points.rkt
- src/sandbox.rkt
- src/web/make-report.rkt
- src/web/report.css
This is a truly ancient fix. Way back in the day, Herbie did not use bits of error as its error measure; instead it used relative error. This lead to a problem any time the exact answer was zero, or the inexact answer was infinity, or something like that. So the Herbie reports of the time showed both error (where that was possible to compute) and also the number of points that should be finite which were actually zero or infinity.
That column has been inactive for years (ever since we moved from relative error to bits error), but it is still in the code, carefully preserved. This commit strips it out.
> No report columns for infinities

- src/core/eggmath.rkt
- src/core/simplify.rkt
This bug was introduced during the refactor of PR #272 
`eggmath.rkt` was not checking if the expression is an fpcore constant when renaming variables to send to the rust side.
> Fix bug with constants in egg-herbie

- src/biginterval.rkt
- src/mainloop.rkt
- src/web/report.css
- src/web/timeline.rkt
The pruning block in the metrics now shows four initial states (new alts, fresh alts, the picked alt, and done alts) and whether each was kept or pruned.
Also fixes a problem in the `==` interval method.
> Better pruning statistics

- src/core/simplify.rkt
Herbie is supposed to fall back on the `regraph` package if `egg-herbie` is not installed. Previously, Herbie would fail to compile without `egg-herbie`. This PR fixes the bug by dynamically importing from `egg-herbie`.
> Dynamic require for egg-herbi

- src/core/alt-table.rkt
- src/mainloop.rkt
Right now, pruning only sort of tries to ensure that simpler alts will be chosen when available by pruning. This commit mostly fixes that while also marginally speeding up pruning. The main tweak is to track the simplest alt available at every point and, in cases where an alt is tied at some points, only consider it if it is simplest at at least one point.
> Select for simpler alts when pruning

- src/core/reduce.rkt
- src/core/regimes.rkt
- src/points.rkt
- src/syntax/test-rules.rkt
Our use of NAN as a failure value currently breaks `posit` support. This should fix that.
> Fix use of NAN as the failure value in ival-eval

- src/core/alt-table.rkt
- src/points.rkt
- src/programs.rkt
- src/web/timeline.rkt
I often find that `eval-prog` is between 10% and 20% of Herbie's runtime. Almost all of that happens in `atab-add-altns`, because we have to evaluate each `alt` to decide which ones to keep. In extreme cases, that means evaluating 20,000 expressions to figure out which one expression to keep.
This PR speeds this up by adding a `batch-eval-prog` function that evaluates multiple expressions on the same point. Since candidates are mostly quite similar, they'll have a lot of shared subexpressions, and `batch-eval-prog` can avoid recomputing them.
> Batch eval-prog

- .github/workflows/hamming.yml
- infra/travis.rkt
This adds a matrix of tests to run both `binary32` and `binary64` for the Hamming tests. A nice side benefit is that the single-precision tests run really fast (presumably because there just isn't much to do).
The `:herbie-expected` flags are weaker than intended, but on the other hand we only have two of them. We might want to totally kill this at some point and just use targets.
> Test single-precision mode

- src/core/simplify.rkt
This PR accounts for recent changes in the `egg-herbie` package by freeing the FFI rules. `egg-herbie` switched to manual memory management.
> Free the FFI rules after we're done with them

- src/programs.rkt
The function `unfold-let` had a bug where if the RHS of a variable assignment involved a let, the let would not be unfolded.
This is a simple fix.
> Fix substitution when eliminating let bindings

- bench/hamming/quadratic.fpcore
- bench/hamming/rearrangement.fpcore
- src/float.rkt
- src/syntax/rules.rkt
Single-precision was broken because, for some reason, `equal?` doesn't work for `+inf.f` and friends. I tweaked `special-value?` so that it now uses `=` in those cases. This caused some expressions to break, and I looked into them, adding `herbie-expected` where necessary.
> Important fixes to single-precision support

- infra/convert-json.rkt
The `infra/convert-json.rkt` file converts Herbie JSON files to FPCores, including support for `:name`, `:spec`, `:pre`, and `:precision`, as well as an optional flag that converts pre-FPCore JSON dumps.
> Script to convert demo files to FPCore

- src/float.rkt
- src/interface.rkt
- src/mainloop.rkt
- src/points.rkt
- src/programs.rkt
- src/syntax/syntax-check.rkt
- src/syntax/syntax.rkt
- src/syntax/type-check.rkt
- src/syntax/types.rkt
- src/web/plot.rkt
This PR continues the cleaner separation of types and representations in preparation for MPMF Herbie, focusing this time on posit and complex plugins. Posit representations previously used their own types since the old `real` type assumed all values satisfied Racket's `real?` predicate. Now, posit reprs are of type `real` and certain complex operations are handled better.
> Update type/repr infrastructure for better plugins

- src/common.rkt
- src/core/localize.rkt
- src/core/regimes.rkt
- src/core/simplify.rkt
- src/datafile.rkt
- src/float.rkt
- src/function-definitions.rkt
- src/interface.rkt
- src/plugin.rkt
- src/programs.rkt
- src/sandbox.rkt
- src/syntax/rules.rkt
- src/syntax/syntax-check.rkt
- src/syntax/syntax.rkt
- src/syntax/test-rules.rkt
- src/syntax/type-check.rkt
- src/web/plot.rkt
- src/web/thread-pool.rkt
It makes sense to define a general representation for certain number systems such as fixed-point numbers. To actually use an instance of this representation, one must specify certain parameters, e.g. `(fixed 3 4)`, but these parameters will only be known after FPCores are read in. 
This PR improves the current plugin interface by adding the ability to generate representations, operators, and rules during runtime. This will allow plugins to define 'templated' representations and rules.
> Better plugin interface and templated representations

- src/core/simplify.rkt
Now that `egg-herbie` is the default, it would be nice if you were not required to install `regraph` in the same way as you are not required to install `egg-herbie`. This PR fixes it by dynamically requiring `regraph`.
> Make regraph optional

- src/datafile.rkt
- src/programs.rkt
- src/sandbox.rkt
- src/web/run.rkt
- src/web/thread-pool.rkt
- src/web/timeline.rkt
Herbie has accumulated a few crashing bugs in recent months. This PR fixes all but one. For certain benchmark suites, Herbie may segfault unexpectedly. The cause of this bug is unknown. Hopefully, this gets fixed in the next Racket version.
> Fix crashes

- src/core/alt-table.rkt
- src/mainloop.rkt
- src/programs.rkt
- src/syntax/rules.rkt
This PR introduces the 'retired alts' idea. Any alts removed from the alt table are designated 'retired' and will not be actively used in further iterations. However, they will now be available when regimes chooses branch expressions. This idea improves accuracy by a small bit. Other changes include a new cost metric, a few rules, and cleaner rules groups.
> Keep alts removed from alt table for regimes

- src/web/demo.rkt
This PR fixes is. h/t @chandrakananandi
> The "install Herbie" link on the demo page is broken

- .github/workflows/egg-herbie.yml
- .gitignore
- Makefile
- README.md
- egg-herbie/.gitignore
- egg-herbie/Cargo.toml
- egg-herbie/LICENSE
- egg-herbie/Makefile
- egg-herbie/README.md
- egg-herbie/deploy.sh
- egg-herbie/egg-interface.rkt
- egg-herbie/info.rkt
- egg-herbie/main.rkt
- egg-herbie/src/lib.rs
- egg-herbie/src/math.rs
- egg-herbie/src/rules.rs
- egg-herbie/tests/tests.rs
- egg-herbie/to-egg-pattern.rkt
- src/info.rkt
- www/doc/1.4/installing.html
`egg-herbie`, the `egg` interface for Herbie, previously lived here: https://github.com/herbie-fp/egg-herbie
However, it has become clear that Herbie is tightly coupled to the rust code that runs the e-graph using `egg`, and also to the racket interface to that rust code.
So `egg-herbie` will now live as a package in the same repository.
Users of Herbie have two options for installing Herbie, and the README and website have been updated to reflect them.
One is to `raco pkg install` Herbie in the `src` directory. Installing this way uses the old `egg-herbie` repository to redirect to pre-built binaries for `egg-herbie`.
The second requires that Rust be installed. Running `make install` in the `herbie` directory will build the local `egg-herbie` and install it.
> Merge egg herbie into herbie repository

- src/common.rkt
- src/config.rkt
- src/core/reduce.rkt
- src/core/regimes.rkt
- src/errors.rkt
- src/float.rkt
- src/function-definitions.rkt
- src/herbie.rkt
- src/mainloop.rkt
- src/programs.rkt
- src/sampling.rkt
- src/sandbox.rkt
- src/searchreals.rkt
- src/syntax/read.rkt
- src/syntax/rules.rkt
- src/syntax/sugar.rkt
- src/syntax/syntax.rkt
- src/syntax/test-rules.rkt
- src/timeline.rkt
- src/web/common.rkt
- src/web/history.rkt
- src/web/make-graph.rkt
- src/web/pages.rkt
- src/web/thread-pool.rkt
- src/web/timeline.rkt
This PR of tiny fixes:
- Fix infinite-value handling in fixpoint representations
- Possibly fix some race conditions
- Fix crashes when there are no valid inputs
- Remove `precision:double`
- Remove a bunch of unused or dead code
- GZip JSON files so they take up less space
- Fix the `--num-enodes` and `--num-analysis` flags
- Reorganize some code
> Many Small Fixes

- Makefile
Running `make install` uninstalls any exising `egg-herbie` package and re-installs the local version. This causes dependency problems, which this PR avoids using the raco pkg `--force` option.
> Fix re-install of egg-herbie through makefile

- src/common.rkt
- src/core/taylor.rkt
- src/mainloop.rkt
One of Herbie's core rewrites is taking the series expansion of an expression (like a Taylor expansion, though we actually use bounded Laurant series). Right now, Herbie uses a multivariate series expansion, but it seems that this is actually unnecessary: successive Herbie iterations can handle multiple variables if it's really necessary, and in practice it seems like it basically never is.
This commit switches Herbie from multi-variate to univariate series expansions. It also adds support for "streaming" expansions, which do more or fewer terms based on what helps the most. That turns out to be necessary because univariate expansions let us get more terms, which isn't always a win. A final bonus from this branch is the ability to delete the large, ugly `approximate` function, which did …
> Series expand one variable at a time

- .github/workflows/tests.yml
- .github/workflows/tools.yml
- Makefile
- egg-herbie/egg-interface.rkt
- egg-herbie/main.rkt
- egg-herbie/src/lib.rs
- src/alternative.rkt
- src/core/alt-table.rkt
- src/core/simplify.rkt
- src/mainloop.rkt
- src/symmetry.rkt
- www/doc/1.5/faq.html
- www/doc/1.5/installing.html
This PR enhances Herbie's use of egg-herbie. It improves the information shown in the report and also streams values from each egraph iteration as alt programs, so that intermediate simplifications are also candidate programs.
Todo:
> Egg interface fixes

- src/conversions.rkt
- src/core/regimes.rkt
- src/interface.rkt
- src/programs.rkt
- src/syntax/rules.rkt
- src/syntax/syntax.rkt
- src/syntax/type-check.rkt
- src/web/make-graph.rkt
- src/web/report.css
This PR speeds up Herbie by ~1.5x by making the representation interface a little saner and adding operator info caching in batch-eval-prog. Other changes include: cleaner rule names, more specific errors for bad parametric operators, and other small fixes.
Also caught a few bugs in the plugins with these changes.
> Faster eval prog and series

- src/web/demo.rkt
This PR fixes a bug that crashes the web demo instead of displaying a useful error
> Fix 'no formula' web demo crash

- src/common.rkt
- src/conversions.rkt
- src/core/reduce.rkt
- src/float.rkt
- src/float32.rkt
- src/interface.rkt
- src/plugin.rkt
- src/syntax/sugar.rkt
- src/syntax/syntax-check.rkt
- src/syntax/syntax.rkt
- src/syntax/test-rules.rkt
- src/syntax/type-check.rkt
- src/web/plot.rkt
This PR splits the operator table (and constant table) into two distinct tables: "abstract" and "implementations". Each operator in the abstract table defines the bigfloat, interval, nonffi functions associated with each operator so we don't need to redefine those each time. Every implementation defines the float functions and input/return types and inherits from the abstract operator it implements. Implementations can override a property. All plugins have been updated and are no longer compatible with older versions of Herbie. Includes some bug fixes.
> Split operator and constant table

- src/core/localize.rkt
- src/core/matcher.rkt
- src/core/reduce.rkt
- src/core/simplify.rkt
- src/core/taylor.rkt
- src/function-definitions.rkt
- src/programs.rkt
- src/syntax/sugar.rkt
- src/syntax/syntax-check.rkt
- src/syntax/syntax.rkt
- src/syntax/type-check.rkt
Basically only use `constant?` inside a big match statement anyway, and then often need a nested `if` to check for numeric constants separately.
> Change constant? to not include literal numbers

- .github/workflows/tests.yml
- src/conversions.rkt
- src/core/localize.rkt
- src/core/taylor.rkt
- src/debug.rkt
- src/errors.rkt
- src/function-definitions.rkt
- src/interface.rkt
- src/sandbox.rkt
- src/syntax/sugar.rkt
- src/syntax/syntax.rkt
- src/syntax/types.rkt
- src/timeline.rkt
This PR resolves some long-standing issues with multi-threading.
- most shared mutable hash tables have either been changed to immutable tables or mutable hash tables using `eq?`-based key comparisons
- resetters make sure to initialize new hash tables rather than clear the old ones
- introduces a workaround for Racket CS <= 8.2 to resolve a [bug](https://github.com/racket/racket/commit/54d5b26b6e1be709a25e04d53eedda8077f60f52) involving `racket/place`
> Ensure thread-safe operations

- src/binary32.rkt
- src/binary64.rkt
- src/bool.rkt
- src/config.rkt
- src/fallback.rkt
- src/interface.rkt
- src/plugin.rkt
This PR creates a new internal plugin called the fallback plugin (invoked by `:precision racket`). This plugin is essentially the same as `binary64` except it uses Racket's math library. The bad fallback code within the `binary64` and `binary32` plugins has been removed. If Herbie cannot find certain libm functions, it will produce an error if these functions are used. In addition, `numerics` rules have been enabled by default.
> Fallback plugin / numerics rules on by default

- src/web/demo.rkt
- src/web/make-report.rkt
The `make-report-page` takes an extra parameter now but no one told `demo.rkt`.
> Fix a bug wherein demo results were being silently lost

- src/binary32.rkt
- src/binary64.rkt
- src/errors.rkt
- src/herbie.rkt
- src/mainloop.rkt
- src/sandbox.rkt
- src/syntax/syntax-check.rkt
- src/syntax/type-check.rkt
- src/web/demo.rkt
This PR fixes multiple bugs found in recent demo crashes as well as issue #396. These fixes include
- raise error with malformed FPCore without crashing
- early exit in demo on failed input
- disable operators that can't be loaded through ffi
- add missing type check
- load representations for unit tests to work
In addition, warnings are now aggregated and must be manually printed through `print-warnings`.  This allows warnings to be grouped.
> Fix multiple bugs

- src/core/simplify.rkt
This PR removes the `dynamic-require` calls in `simplify.rkt` and replaces them with `lazy-require`. I've tested and this seems to work with both `regraph` and `egg-herbie`, and if `egg-herbie` is missing it only loads and runs `regraph`.
Another benefit of this is it declares the dependency somehow to Racket, whereas `dynamic-require` doesn't. I'm not sure what this actually does for us but it's probably good.
> Use lazy-require in the simplify code

- infra/make-index.rkt
- infra/publish.sh
Right now, `make-index.rkt` requires the `report.json` file from all reports ever run to be present on the computer where it is run. Frankly, this is insanity—that data is being constantly sent to and from `uwplse.org`, it is bulky, it is slow. So in this new system, only cache files are sent back and forth, and the only files you need locally are the ones not currently in the cache file.
Overall, this PR makes `make-index` run quickly, require much less data storage, and in general use a sane instead of an insane architecture.
> Make make-index read and write from cache, not files

- src/common.rkt
- src/mainloop.rkt
- src/syntax/read.rkt
- src/syntax/syntax.rkt
This PR replaces each "table" with a simple struct definition and a hasheq table from symbols to that struct. This removes a bunch of code which frankly was kind of dumb. Negative diff PR!!!
> Remove "tables" entirely from syntax.rkt

- infra/regression-chart.js
- src/core/localize.rkt
- src/cost.rkt
- src/mainloop.rkt
- src/programs.rkt
- src/reprs/binary32.rkt
- src/reprs/binary64.rkt
- src/reprs/bool.rkt
- src/reprs/fallback.rkt
- src/sampling.rkt
- src/syntax/rules.rkt
- src/syntax/sugar.rkt
- src/syntax/syntax-check.rkt
- src/syntax/syntax.rkt
- src/syntax/type-check.rkt
This fairly simple commit replaces the variary and/or/comparison operators with a simple expander. The expander is generally smart, in that it is linear except in the case of `!=` where it does generate quadratically-many comparisons. I do not expect that variary `!=` is used enough for this to matter.
> Remove all variary operators

- src/config.rkt
- src/core/alt-table.rkt
- src/core/localize.rkt
- src/mainloop.rkt
- src/patch.rkt
- src/sandbox.rkt
This PR moves all patch table code to a separate file and provides an API for the mainloop to enqueue expressions, run improvements, and extract patches.
> Move patch table code to separate file

- src/config.rkt
- src/core/regimes.rkt
- src/mainloop.rkt
- src/patch.rkt
This PR cleans up some messy code from #407 and adds alt count info to the timeline.
> Cleanup mainloop / patch table split

- src/conversions.rkt
- src/core/alt-table.rkt
- src/cost.rkt
- src/mainloop.rkt
- src/programs.rkt
- src/syntax/rules.rkt
- src/syntax/sugar.rkt
- src/syntax/syntax.rkt
- src/syntax/type-check.rkt
This PR removes the `parametric-operators` and `parametric-operators-reverse` hash tables. In its place are new methods like `operator-all-impls`, `impl->operator`, and a few others.
In doing this refactor, I also removed a number of code blocks that deal with variary operators, and also removed some obsolete data like `*unknown-ops*`.
> Remove the parametric-operators hash tables

- infra/make-index.rkt
- infra/publish.sh
When I rewrote the nightly code to use digests, I forgot to fix my handling of paths, which are used to derive the links that are placed in the web page. This PR fixes that issue, by using relative paths and allowing renaming.
> Fix paths in nightlies

- src/shell.rkt
- src/syntax/read.rkt
Right now, if you write a number in decimal format in Herbie's input, like `3.1415`, Herbie interprets that as an inexact floating-point value, which hinders optimization because Herbie avoids computing with it. This changes Herbie's reader to treat that input as the fraction 31415/100000, an exact real value, which Herbie can then compute on and optimize.
> Read decimals exactly

- README.md
- src/web/common.rkt
- www/index.html
This changes some of the README and web files, but not documentation for older versions. Github will continue redirecting those links, so I think it's not a problem.
> Rename the repo to herbie-fp/herbie

- src/web/pages.rkt
This PR modifies `src/web/pages.rkt` to provide a binary result file at the webpage `.../points.json.gz`. (Although it is planned to receive this object in the web interface, no other files have yet been added or modified.) Running `gunzip` on this binary provides a JSON string with the following fields:
```js
{
points, // array of value->json printed values (from `newpoints`)
exacts // array of value->json printed values (from `exacts`)
}
```
This should allow for client-side result graphing and the client-side measurement of new functions.
For a representative example, JSON output size was 297KB while the gzipped binary was 137KB. This represents 160KB saved per request.
> Add compressed points output.

- src/web/demo.js
- src/web/demo.rkt
- src/web/main.css
This PR modifies `src/web/demo.js`, `src/web/demo.rkt`, and `src/web/main.css` to allow users to specify input range preconditions in the default mathjs interface.
Ranges appear for each parsed input variable and are specified through pairs of input boxes. If users enter incorrect values in the ranges (non-numbers, numbers outside the ranges, out-of-order ranges), appropriate error messages are displayed. To avoid showing errors while users are working, no errors are displayed for legitimate partial ranges, but users must specify both sides of each range in order to submit the form. Unfilled ranges are highlighted with light blue. Single-point ranges show a yellow-highlighted warning message, but still allow form submission. Once input, values for the range of a particular variable name …
> Add input range preconditions in the default mathjs interface.

- src/core/alt-table.rkt
This PR changes the "all-alts" field in the alt table from a set to a list, so that they'll be sorted identically in different runs and therefore so that regimes is more deterministic.
> Sort alts coming into regimes, so that things are more deterministic

- egg-herbie/Cargo.toml
- egg-herbie/src/math.rs
Change `egg-herbie` cost function: do not extract `pow` nodes with fractional (odd denominator) exponents. This should clean up some of Herbie's output and seems to help the soon-to-be-merged `egg-rr` branch.
> Penalize `pow` with fractional (odd denominator) exponents

- README.md
- src/config.rkt
- src/core/matcher.rkt
- src/core/simplify.rkt
- src/info.rkt
- www/doc/1.5/installing.html
- www/doc/1.6/faq.html
- www/doc/1.6/installing.html
This PR removes `regraph` from Herbie for good! For the last two years, `regraph` has been part of Herbie's code base purely as a fallback system when `egg` could not be installed. Now that `egg` has become increasingly important to Herbie's functionality, it's time to remove `regraph`. 
- simplify and recursive rewrite has been cleaned up now that `egg` is not optional (no more lazy requires)
- legacy recursive rewriter has been removed
- installation section on the README is more descriptive to avoid installation problems
> Remove regraph

- README.md
- egg-herbie/Cargo.toml
- egg-herbie/src/lib.rs
- egg-herbie/src/math.rs
- egg-herbie/src/rules.rs
- www/doc/1.6/installing.html
This PR updates `egg` to version 0.8.1 as well as other dependencies of `egg-herbie`.
> Update egg to 0.8.1

- src/web/make-graph.rkt
- src/web/resources/report.css
This allows the browser to break katex display expressions on spaces that are not inside of parenthesized expressions.
This doesn't solve display issues where the majority of the expression is parenthesized, but it should generally solve precondition overflow. As written, this will affect the display of katex expressions anywhere on the page.
The code is copied from https://katex.org/docs/issues.html.
Note that this fix swaps the HTML loading order of the katex CSS file and the report CSS file so the report CSS comes later and its rules are prioritized.
> Partial fix for fitting KaTeX expressions inside surrounding boxes.

- src/core/taylor.rkt
- src/programs.rkt
This PR fixes the taylor-cbrt implementation and uses `sqrt` and `cbrt` for `(pow _ 1/2)` and `(pow _ 1/3)` rather than the default.
> Taylor: fix cbrt and fast paths for 1/2 and 1/3 powers 

- src/core/matcher.rkt
- src/core/regimes.rkt
- src/core/simplify.rkt
- src/mainloop.rkt
- src/patch.rkt
- src/timeline.rkt
- src/web/timeline.rkt
This PR tweaks the timeline with the hope of truly, for real, finally replacing the debug log.
> Timeline improvements

- .github/workflows/plugins.yml
- .github/workflows/tests.yml
- infra/bench/posit-pherbie.fpcore
- infra/travis.rkt
- src/conversions.rkt
- src/core/matcher.rkt
- src/pareto.rkt
- src/patch.rkt
- src/points.rkt
- src/syntax/syntax.rkt
#446 introduced problems for Pherbie that unfortunately were not caught. This PR patches these issues, makes conversion syntax slightly saner, and adds an additional test to CI.
Long term, there should be a better solution to applying rewrites of the form `x -> f(x)` since this was causing issues even without introducing precision changes. The current solution is: if multiple representations with type `real` are loaded, then these rewrites are not applied in `egg` and instead go through a separate path using `rewrite-once` which is significantly less powerful.
> Fix Pherbie

- Dockerfile
We use a multistage build to avoid including Rust in the final image.
Also fixes an issue which may have prevented users from accessing
the web demo from the container by including the --public flag.
Adds EXPOSE annotation to note that port 80 is exposed.
> Switches to building egg-herbie with Rust.

- src/core/regimes.rkt
- src/pretty-print.rkt
I was looking at a recent Herbie report and was stunned to discover that `option-on-expr` (the main part of regimes) spends 40% of its runtime in `errors`. It turns out that regimes is wasteful in two ways:
1. It uses `errors` instead of `batch-errors`, meaning that it doesn't get the benefits of common subexpression elimination
2. It recomputes `errors` for every branch expression, even though the only thing that changes is the sort order
This PR fixes both problems; I expect it to speed up regimes by 1.5x or so and Herbie overall by about 4%.
> Speed up regimes by batching calls to `errors`

- src/errors.rkt
- src/reprs/binary32.rkt
- src/reprs/binary64.rkt
- src/reprs/fallback.rkt
- src/syntax/syntax-check.rkt
- src/syntax/syntax.rkt
- www/doc/1.5/faq.html
- www/doc/1.6/faq.html
This PR deprecates the Bessel functions, i.e. `j0`, `j1`, `y0`, and `y1`. Input expressions containing these operators will trigger warning messages. Warnings when loading unsupported operators have been removed.
> Deprecate Bessel functions

- src/core/reduce.rkt
This PR makes `reduce.rkt` dumber, thereby making it much faster. A bit of backstory. The reducer, or backup simplifier, is used only in the series expander. It's much faster than e-graph based simplification, but also a lot dumber. In fact, it predates the e-graph based simplifier—it was written in summer 2014 when Alex and I were looking to replace the existing simplifier, which was very brittle. Anyway, this means it was originally written to be Herbie's general-purpose simplifier, at a time when we thought we needed a pretty smart simplifier. This means that it's probably working too hard for its current task.
In this PR, I remove the reducer's understanding of distributivity, meaning that it will no longer expand `(a + b) * c` into `a * c + b * c`. This is bad in some ways, because …
> Remove distributivity and pow-distributivity from reducer

- src/core/alt-table.rkt
- src/core/regimes.rkt
- src/points.rkt
- src/sandbox.rkt
- src/web/plot.rkt
This PR replaces  `oracle-errors` and `baseline-errors` with a new inlined implementation in terms of `batch-errors`. It turns out that when run in Pareto mode, Herbie spends almost 30% of its runtime in `oracle-errors`, basically because it evaluates every useful alt Herbie has ever seen on every point. By using `batch-errors` we avoid re-evaluating an alt multiple times on the same point, and also gain the benefit of some common subexpression elimination.
Along the way, this PR also implements `errors` in terms of `batch-errors` and changes the later to use lists in place of vectors (it turns out all callers convert the vectors to lists anyway).
> Use `batch-errors` in place of `oracle-errors` and `baseline-errors`

- src/core/alt-table.rkt
This PR totally rewrites the `minimize-alts` method, replacing a purely-functional with a mostly-imperative implementation. This dramatically reduces overhead, resulting in massive speedups.
The key to this is to simplify the `point->alts` immutable hash table in an alt table with a mutable "flat-list", which is a vector of mutable sets. This is _way_ easier to update, since we can do so mutably and without allocating much. Now, unfortunately, this results in quite a bit more code, because we need to keep around most of `minimize-alts`, in particular the `rm-alts` method (renamed to `atab-remove*`), to actually create a new alt table once we've decided which alts to remove.
One question all this work does raise is whether we actually need to minimize the alts. I'm not totally sure of …
> Speed up `minimize-alts`

- src/ground-truth.rkt
- src/info.rkt
- src/reprs/binary32.rkt
- src/reprs/binary64.rkt
- src/reprs/fallback.rkt
- src/sampling.rkt
- src/syntax/syntax.rkt
- src/syntax/test-rules.rkt
- src/web/resources/demo.js
- www/doc/1.7/faq.html
This PR is related to [herbie-fp/rival PR #7](https://github.com/herbie-fp/rival/pull/7), which implements `ival-lgamma` and `ival-tgamma`. To that end, this PR removes support for the Bessel functions and uses interval implementations for the Gamma functions, thereby ensuring that all Herbie-supported operators have interval variants. The PR thus also removes all fallback options if an interval implementation is not available.
> Use the interval implementation of the gamma functions

- Makefile
Nightlies were failing because `update` actually always needs the new `egg-herbie` routine to run first. This is just what `install` does now, so I removed the old conditional code and just included install as a dependency of the nightly target.
> Simplify nightly make routine--just install then run nightly.sh

- Makefile
This fixes 2 raco-related bugs in the Makefile that interfere with the routine of the nightly runs.
Bug 1 reproduction:
* Clone herbie into 2 directories
* make install in the first directory
* remove the first directory
* make install in the second directory -- this fails
Cause: trying to install a new egg-herbie leads `raco pkg` to panic because the directory for a dependent package (herbie) no longer exists. This occurs on the nightly server when a branch is deleted and the directory the branch was cloned to happens to be the last directory from which herbie was installed.
Solution: always remove the herbie and egg-herbie packages before installing.
I'm not sure if this is something the Racket package manager should be smarter about. It is related to …
> Fix raco calls in makefile

- infra/travis.rkt
- src/core/regimes.rkt
- src/sandbox.rkt
- src/web/make-graph.rkt
This PR is complicated.
Regimes is the pass that determines which alt to use on which point. Regimes metrics measure how good a job it does. Right now, this measurement is done after Herbie is done, on the resampled points. To do so Herbie measures an _oracle_ value by finding the best alt on any new point. It also measures a _baseline_ value by picking the best single alt overall. The regime metric is then somewhere between these two values (hopefully).
This PR changes the calculation to use _old_, not _new_, points. This makes it faster, because we already evaluate all alts on all points during regimes, and can now reuse those points for metrics.
Now the tricky bit is that this changes the meaning of those metrics. Regimes can fail by _underfitting_, where there's a program that is …
> Measure regimes metrics during regimes

- .github/workflows/plugins.yml
- .github/workflows/tests.yml
- src/core/alt-table.rkt
This PR fixes a major bug for Pherbie in the alt-table implementation, where alts were added and not pruned away, even if they were strictly worse than other alts. Basically, when an alt was added to the alt-table, instead of checking whether it's dominated by any other alt, we just checked whether it was more accurate than all other alts with exactly that cost. Typically, there wasn't another alt with the same cost, so often it was preserved for no reason. The result was that alt-tables would be too large, so all sorts of O(alts) processes like pruning and regimes would take way too long.
The implementation here is a little naive, in that it involves a full scan of the Pareto curve, but even so it speeds up `2tan` by about 30% (this is the benchmark I've been focusing on). It might also …
> Fix major alt-table bug, leading to more speed-ups

- src/core/alt-table.rkt
- src/pareto.rkt
This PR refactors the alt table to change the representation of Pareto curves from some crazy hash table thing to a simpler sorted list. The goal is to eventually move all the parts of Herbie that use Pareto curves to use the same Pareto curve library, though that’s not in this PR. Along the way, this PR also speeds up pruning, because the hash table representation was expensive to create and modify.
> Refactor alt table

- src/core/reduce.rkt
- src/programs.rkt
It turns out that in rare cases, Herbie tries to simplify `(cbrt +inf.0)` using the backup simplifier, which crashes it (because Herbie tries to call `inexact->exact` on `+inf.0`, a weird edge case). This PR fixes it by moving all of this tricky logic to `eval-application`.
I'm not even sure what I did to see this bug. It is super duper rare.
> Fix rare bug

- src/herbie.rkt
- src/sandbox.rkt
- src/web/run.rkt
This PR make `--profile` a no-op; it is always on for `report` mode (and `rerun` mode) and off otherwise. It also changes the internals of profiling to not redirect standard out, which should make it less likely that we'll eat tracebacks or bugs.
> Turn on profiling by default & don't redirect stdout

- src/config.rkt
- src/sampling.rkt
- www/doc/1.7/options.html
The tweaks are:
- Start sampling with 256, not 128, mantissa bits. It turns out that MPFR isn't much faster with 128 bits than 256 bits (mostly fixed costs I guess) so this lets us skip an iteration, saving time overall. I guess?
- Use 8000 enodes in eclass steps. This leads to more generated expressions and also simpler results (both good). Increasing this further is really bad for performance, however, since we start discovering a lot of unsound merges and need to do the rewrite step much more slowly.
- Use 12, not 14, analysis iterations. This parameter is exponential, so the tweak reduces analysis time about 4x without increasing sampling time much at all.
> Conservatively tweak some defaults to get better results

- src/web/demo.rkt
- src/web/resources/main.css
This will hopefully help folks who see a crashed demo from being disappointed. Plus it makes the SLA clearer.
> If the Herbie demo crashes, show a helpful message.

- src/sandbox.rkt
A tiny fix for when a benchmark 1) times out; 2) during sampling; 3) to make sure it generates a nicer table.
> Compact sampling table on timeout

- .github/workflows/distribute.yml
- .github/workflows/egg-herbie.yml
- .github/workflows/plugins.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- .github/workflows/tools.yml
- .github/workflows/unit-test.yml
- src/datafile.rkt
- src/web/make-report.rkt
The others include:
- Write the results json atomically, in case the server runs out of disk space again
- Use `8.5` instead of `stable` for the CI because `8.6` has a bug
- Hide a broken link on reports pages
> Work around Racket 8.6 bug in CI, and others

- src/pareto.rkt
- src/web/make-report.rkt
This PR adds new functions to the Pareto frontier library and adds new functions.
The interface is now:
pareto-map : frontier, fn -> list => classic map idiom but over a frontier
pareto-union : frontier, frontier -> frontier => merges two frontiers (like "minimum")
pareto-convex: frontier -> frontier => returns the convex subset of a frontier
pareto-minimize: points -> frontier => returns the Pareto-optimal subset of points
pareto-combine: adds multiple frontiers (see ARITH '21 paper)
> Rewritten Pareto frontier library

- pareto
- src/datafile.rkt
- src/web/make-graph.rkt
- src/web/make-report.rkt
- src/web/pages.rkt
- src/web/plot.rkt
- src/web/resources/arrow-chart.js
- src/web/resources/report.js
This PR replaces usage of native racket plot generation with Observable Plot. 
All plots now have both a dot graph and line graph.
Plumbing details:
- For each benchmark, the benchmark name is passed through the `data-benchmark-name` attribute so the js side knows which test data it's looking for in the `results.json`
- There is a new top-level field named cost-accuracy in the `results.json` object where `cost-accuracy[0]` is a pair representing the domain and range, `cost-accuracy[1]` is the first point, and `cost-accuracy[2]` is an array of pareto-optimal points.
Related code has been moved from `make-report.rkt` to `datafile.rkt` but this adds a couple dependencies to `datafile.rkt`.
> Svg pareto plots

- src/web/demo.rkt
Basically, write the JSON file out to a temporary file, then rename it over the existing file. This makes sure that if we're out of disk space, the `results.json` file is still written out in a valid way.
> Avoid butchering the JSON file when we're out of disk

- bench/libraries/rust.fpcore
Rust's math library [reimplements][rust-libm] `asinh`, `acosh`, and `atanh`. I'm not sure why it doesn't use `libm`'s implementation; I assume it's about supported platforms.
In any case, @finnbear discovered that their implementations are woefully inaccurate (see https://github.com/FPBench/FPBench/pull/118).
This PR adds these implementations as a benchmark in `libraries/rust.fpcore`. The benchmarks are available in 32-bit and 64-bit mode, are annotated with the relevant precondition, and also have a `:herbie-target` which is my hand-written improved version.
[rust-libm]: https://github.com/rust-lang/rust/blob/1ea4efd0656599f824e2567a5b7a95454f701c03/library/std/src/f64.rs#L883
> Added FPCore for Rust's `{f32,f64}::a{sin,cos,tan}h`

- www/main.css
This PR swaps out the fonts with new, standard Herbie brand fonts:
- Ruda medium for headings
- IBM Plex Serif and Mono for body text
Basically this makes the docs look a little better & more coherent.
> Change the fonts used on the docs pages

- src/core/regimes.rkt
- src/mainloop.rkt
This PR removes calculating sound options; we are always choosing `unsound-option` over `sound-option` in `infer-splitpoints` so there is no need to recalculate sound options.
Also removes an unused parameter in `mainloop.rkt` `pareto-regimes`' inner loop.
> Don't calculate sound options

- egg-herbie/Cargo.toml
- src/core/reduce.rkt
- src/core/taylor.rkt
This PR is for @oflatt. It removes all uses of `rules.rkt` from `reduce.rkt`, basically by hard-coding the relevant bits as source code.
I'll add that I'm not actually sure this stuff is necessary, and maybe getting rid of it entirely (along with other parts of `reduce.rkt` would be better), but definitely this change is safe.
> Don't use rules for fast reduction

- src/core/egg-herbie.rkt
- src/soundiness.rkt
- src/web/history.rkt
- src/web/resources/report.css
Renders the egg proofs for simplify (added in #485). Proofs are collapsible and show average error. Additional information visually displayed upon hovering over error including direction, points better/worse.
> Render proofs

- src/sandbox.rkt
- src/timeline.rkt
Basically, `get-test-result` currently does two jobs. First, the "meat" samples, runs Herbie, measures the results, and stuffs all of that into a `test-result` struct. And second, the "wrapper" handles errors, timeouts, the timeline, profiling, and so on. For our long-term goal of creating a "job" abstraction to support Odyssey, separating out this second "wrapper" task into its own method is useful. This PR starts on that, separating the "meat" into a new `run-herbie` function that `get-test-result` calls directly.
> Refactor `get-test-result` to split Herbie code from sandbox code

- egg-herbie/src/lib.rs
- src/config.rkt
- src/core/egg-herbie.rkt
- src/soundiness.rkt
- src/web/history.rkt
This PR moves proof flattening to the Racket side and limits the number of steps it flattens.
> Fix OOM due to large proofs when flattening

- .gitignore
- egg-herbie/src/lib.rs
- infra/publish.sh
This basically migrates reports from `herbie.uwplse.org` to `nightly`, which should fix our constant annoying disk space issues.
> Update the nightly script to use the new `nightly-results publish` command

- src/web/demo.rkt
It was using `rename-file-or-directory` incorrectly.
> Fix stupid bug in demo

- www/doc/error.html
The page covers:
- What is rounding
- What bits of error means
- What average error means
- Which inputs are valid
- How inputs are distributed / sampled
In the process, it has strengthened my convictions:
- Infinite points should be considered valid
- Average error should be replaced with percent accurate
- There should be a pop-up when you write an input range that spans 0, and there should be a button to add a minimum magnitude.
But anyway, the page describes things as they are; hopefully we can simplify it as we change stuff.
> New documentation page to explain floating-point error.

- infra/nightly.sh
I believe this is because `nightly-results publish` takes the last-uploaded URL and we were re-indexing for no reason.
> Make nightly Slack link to the main report page

- src/web/resources/demo.js
This PR adds support for let expressions in the MathJS input box on the web demo. Users can now write `<var> = <val>; <var> = <val>; ... ; <expr>`. Hopefully, makes for a better experience.
Example shown below:
> Supporting let expressions on the web demo

- egg-herbie/Cargo.toml
This PR bumps the egg version so it includes the performance bug fix
> Fix OOM due to getting sexp of proofs

- egg-herbie/main.rkt
- src/core/egg-herbie.rkt
- src/core/matcher.rkt
- src/core/simplify.rkt
- src/syntax/sugar.rkt
This PR makes the Racket garbage collector manage e-graphs allocated in Rust, and it fixes a double-free bug for the FFI rule cache. Some additional cleanup since `with-egraph` is no longer needed. As a side note, I attempted to have FFI rule structs be automatically reclaimed, but weird bugs started popping up on the Rust-side, presumably use-after-free.
> FFI memory management

- src/web/demo.rkt
Fixed a small bug on the study server branch. When using the demo on localhost. 
Received the following output.
```
Exception
The application raised an exception with the message:
match: no matching clause for #<procedure:parameter-procedure>
Stack trace:
check-status at:
line 315, column 0, in file /Users/zane/Developer/herbie/src/web/demo.rkt
```
> study-server bug on demo

- src/conversions.rkt
- src/core/matcher.rkt
- src/mainloop.rkt
- src/patch.rkt
This PR follows up on #559 to remove the last remnants of `root-loc` handling in `rewrite-once`.
*Short story*: After a series of refactors, there was a lot of code in `patch.rkt` and `matcher.rkt` dedicated to passing around and carefully accounting for a constant value. We can just rip all of that out!
*Long story*: When the recursive rewriter was originally written, it was intended to produce a "proof" of its output by recording each rewrite it applied and the location where it applied it. The recursive rewriter was passed a "root" location, but it would rewrite at various locations below that root. In this case it made sense that the root was passed in and then different locations would come back.
However, when we switched from `rr` to `egg-rr`, we stopped getting back detailed …
> Remove all of the `root-loc` code in `matcher.rkt`

- .github/workflows/tools.yml
- .gitignore
- infra/make-index.rkt
- infra/merge.rkt
- src/web/demo.rkt
- src/web/make-graph.rkt
- src/web/make-report.rkt
- src/web/run.rkt
- src/web/timeline.rkt
- src/web/traceback.rkt
Rename `results.html` to `index.html` in reports so that the results page shows up by default.
> Rename results.html to index.html

- egg-herbie/Cargo.toml
- src/config.rkt
- src/herbie.rkt
This PR addresses issues raised in #541. When `--help` is supplied via the command line, Herbie now prints more details about each of the command line flags.
> More verbose command line --help flag

- src/patch.rkt
- src/points.rkt
This PR fixes an issue discovered in #578, whereby Herbie would sometimes attempt to rewrite a boolean expression and thereby produce expressions like `(*.f64 1.0 (>= b 0))`, which are nonsense and would cause Herbie to crash.
The fix is to just not rewrite expressions whose type isn't `'real` with expansive rules.
> Don't rewrite boolean expressions

- infra/make-index.rkt
- src/datafile.rkt
- src/web/make-report.rkt
- src/web/resources/report.css
- src/web/resources/report.js
- src/web/timeline.rkt
This adds a few more tweaks to the Pareto curve in the reports generated by Herbie.
> More Pareto tweaks

- src/timeline.rkt
This PR restores timeline info to the demo server. In `src/timeline.rkt`, `*timeline*` contains a box which should be reset to the empty list rather than be _replaced_ by a new box.
> Fix demo timeline

- .gitignore
- Makefile
- infra/herbie-demo.service
- src/web/demo.rkt
- src/web/make-graph.rkt
- src/web/make-report.rkt
- src/web/resources/report.css
- src/web/resources/report.js
This PR does a pass over the per-benchmark pareto plot, and also adds a handy table of alternatives:
The end result is, I hope, easier to use and also highlights Herbie's new Pareto capabilities. Plus, the plot now matches all of our new metrics (speedup and percentage accurate) and also matches the overall style.
> Redesign cost-accuracy plot

- src/datafile.rkt
- src/mainloop.rkt
- src/patch.rkt
- src/soundiness.rkt
- src/web/common.rkt
- src/web/history.rkt
- src/web/make-graph.rkt
- src/web/resources/report.css
- src/web/resources/report.js
- www/doc/1.7/release-notes.html
This is a grab-bag report redesign PR. It includes:
- Changing the variable selector in the graph to a dropdown (to be more intuitive)
- Drawing the true Pareto curve (see below)
- Refactoring "loc"s and proofs so that that code is a little simpler.
> Report redesign part 3

- src/mainloop.rkt
This PR rejiggers the main loop a bit, with the aim of making control flow a little clearer and also potentially making it faster.
Basically, right now, Herbie runs for ~4 iterations. In each iteration, it picks ~5 alts (evenly spaced from most accurate to cheapest). Each alt produces ~100 new alts, which are combined and pruned before going on to the next iteration. The iterations run in series. The 5 alts run in parallel. However, that 5-way parallelism isn't batched at the moment, which leads to confusing timelines where certain portions are repeated five times over. It also means less sharing / deduplication than there could be, which in turn likely means somewhat slower runtime.
> Multiple `next-alt`s at once

- src/core/regimes.rkt
This PR is an extension of #591. We can just recompute branch expressions inside `infer-splitpoints` instead of recomputing in `pareto-regimes` and passing them in
> simplified recompute logic

- src/web/make-graph.rkt
- src/web/resources/report.js
Added hyper links to Alternative expressions to make it a little easier to jump and view the alternative expressions.
Also fixed a bug where the number of Alternatives match between `report.js` and `make-graph.rkt`
> Added Links to Alternative expressions

- src/web/common.rkt
- src/web/history.rkt
- src/web/make-graph.rkt
- src/web/make-report.rkt
- src/web/resources/report.css
- src/web/resources/report.js
- src/web/timeline.rkt
This WIP PR is working on redoing the details page completely. Goals include:
- Treat all alternatives equally. Don't highlight the "most accurate alternative" specially
- Make the styling uniform
- Show derivations for each alternative
- Make proofs look good
- Simplify the code to the extent possible 
TODO:
> Redesign the details page

- README.md
Updates the README to remind users that: 
a) Herbie is not necessarily automatically installed in their path, and they may need to add it manually. 
b) They should prefer apt or the official installer over Snap.
>  Add message about adding binary to path and warning against Snap in README.

- src/datafile.rkt
- src/web/demo.rkt
- src/web/resources/404.html
The code is kind of ugly, but this PR replaces #616 without writing anything to the file system.
> Serve `results.json` when running in unsaved web shell

- src/core/regimes.rkt
- src/mainloop.rkt
This PR fixes regime inference changes from #591 that break on the flag ``--no-pareto``.
Makes the parameter ``errs`` an optional keyword parameter. 
``errs`` defaults to an empty hash table; using default values when ``hash-ref`` does not find the key removes the need to externally calculate branch-expressions.
> Regimes fix on no-pareto

- src/float.rkt
- src/points.rkt
- src/web/demo.rkt
Bug originally reported [in this slack thread](https://davidtamaspar-r2y7532.slack.com/archives/C0G44MH4P/p1686595272352829)
Functions with discontinuities (e.g. 1/x from -1 to 1) were causing errors in Herbie (and consequently Oddysey) by creating infinite values that were not properly converted to JSON values. This PR fixes this by 
1. converting them to valid JSON values in pcontext->json, 
2. writing a new json->value function, and:
3. using the json->value function to convert points back into values in json->pcontext.
These changes have been verified using Odyssey to fix the discontinuity errors for: 
- 1/x from -1 to 1.
- 1/(sin(x)) from -1 to 1.
- 1/(exp(x) -1) from -1e308 to 1e308.
> Fix errors from function discontinuities by converting infinities to valid JSON values.

- egg-herbie/Cargo.toml
I followed [this page](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html). The diff was empty and `cargo build`, `cargo test`, and the Hamming benchmark all work. From what I've read about editions, it seems it's crate local, so everything should just work even though `egg` uses the 2018 edition. I basically just want to be able to use `TryInto` from the 2021 standard library in the memory leak fix.
> Migrate egg-herbie to Rust 2021

- src/web/make-graph.rkt
- www/doc/2.0/report.html
The help links for alternatives on the current reports page are broken right now, so I changed the link location for both initial and alternative expressions to "#alternatives" and set the ID of the appropriate paragraph of `www/docs/report.html` ("Initial program and Alternatives") to `alternatives`. I confirmed that this fix works on my system.
> Point initial and alternative options help links to report.html#alternatives.

- src/web/resources/report-page.js
Adds a deep copy to prevent `calculateSpeedup` from modifying the underlying data.
This feels wrong but this was the first solution I could find.
> Fix calculate speedup

- src/programs.rkt
- src/syntax/syntax.rkt
Bigfloat implementations of real operator are not used (except for a single unit test). Removing entirely from Herbie since Rival is preferred in every case.
> Remove bigfloat implementations

- src/core/egg-herbie.rkt
- src/patch.rkt
- src/preprocess.rkt
- src/reprs/bool.rkt
- src/syntax/syntax.rkt
- src/syntax/test-rules.rkt
Expansive rules, e.g., `?x => f(?x)` cause problems with multi-precision expressions in egg since these rules match without checking for the "type" of an expression. As a result, expansive rules are removed from egg if more than one precision is detected, but this usually hurts output accuracy.
Fixing this problem requires a few changes.
- "egg IR" within Herbie to encode variables as operators with type information rather than symbols
- expansive rules are handled separately during rule expansion:
- for all operators: `g(?x ...) => f(g(?x ....))`
- variables: `(var T ?x) => f(T, ?x)` (where `f` is parameterized over a type `T`)
- `make-egg-query` takes an optional context (by default `*context*`) since we need to know the representations of variables. This restricts egg to expressions …
> Fix expansive rules

- bench/hamming/machine-decide.fpcore
- bench/hamming/overflow-underflow.fpcore
- bench/hamming/rearrangement.fpcore
- bench/hamming/series.fpcore
- bench/hamming/temp-rearrangement.fpcore
- src/programs.rkt
Share code between the two compiler versions. The specs version passes around a type that isn't really used, but this might not be the worst thing in the world because @AYadrov might want to modify the types during munge to have variable precision for the trigonometric functions.
> Share code between `compile-specs` and `compile-progs`

- src/web/resources/report-page.js
Adds a simple link to the reports page so you can skip to the timeline without needing to route through graph.html
Wasn't sure on which symbol to use so went with Unicode.
> Adds a link to jump to the Metrics/ Timeline page from the reports page

- src/web/history.rkt
This fixes a small bug with the graph.html page not displaying the Derivations for the alt as shown below.
> Fixed derivation bug on graph.html

- src/common.rkt
- src/compiler.rkt
- src/conversions.rkt
- src/core/egg-herbie.rkt
- src/core/matcher.rkt
- src/reprs/runtime/utils.rkt
- src/syntax/rules.rkt
- src/syntax/sugar.rkt
- src/syntax/test-rules.rkt
This PR includes bug fixes and other non-platforms changes cleaved out from #683.
- `rewrite-once` just didn't work, left out of #672 (unit test included to ensure it works)
- compiler handles strangeness around casts in specs (Herbie IR weirdness, unfortunately the best workaround)
Should make review and merging of #683 easier.
> Fix rewrite once

- src/core/bsearch.rkt
- src/ground-truth.rkt
- src/mainloop.rkt
- src/sampling.rkt
- src/syntax/test-rules.rkt
This PR addresses problems with import cycles encountered by @broughjt with accelerators. Reorganizes procedures in `ground-truth.rkt` and `sampling.rkt`:
- `ground-truth.rkt` - the minimal number of procedures to compute ground truth values
- `sampling.rkt` - all sampling procedures (uses `ground-truth.rkt`)
Hopefully `ground-truth.rkt` can import a minimal number of files.
> Reorganize 'ground-truth.rkt' and 'sampling.rkt'

- src/core/alt-table.rkt
- src/mainloop.rkt
This simplifies a bunch of code in `mainloop.rkt` without I think any downsides. It's split out from #671 .
> Refactors alt picking, so that instead of the atab-pick-alt function that could only pick one alt, it now has a atab-set-picked function that can set multiple alts to picked. This makes code in mainloop.rkt shorter. Additional simplifications also made.
> Replace atab-pick-alt with atab-set-picked

- src/core/regimes.rkt
- src/mainloop.rkt
Basically, when doing `pareto-regimes`, we were recomputing the `err-lsts` every time the set of alts changed, but the set of alts just subsets so there's no reason to actually rerun the alt expressions themselves. Removing this recomputation makes Herbie about 1% faster in my tests, and also makes the interface to `regimes.rkt` a little nicer by moving the pareto case into `regimes.rkt`.
> Remove the `err-lsts` recomputation inside `infer-splitpoints`

- src/sandbox.rkt
Herbie by default runs with a sampling profiler with a sampling rate of 20Hz. This PR ups it to 50Hz to try to get more accurate profiles. Frankly, if 100Hz works I'll try 250Hz and so on; we should go as high as possible before it starts creating a noticeable performance drag.
> Up the profile sampling rate to 100Hz

- src/sandbox.rkt
Well, if 100Hz works, maybe 1000Hz also works. 1000Hz is actually a pretty normal sampling rate (I believe it is the default for Linux `perf` and more accurate profiles is worth investing in. Let's see what the slowdown is actually like; 100Hz was unmeasurable.
> Up the sampling rate to 1000Hz

- egg-herbie/Cargo.lock
Fixes the following build error from running `make install`
```
cargo build --release --manifest-path=egg-herbie/Cargo.toml
Compiling proc-macro2 v1.0.47
Compiling num-traits v0.2.15
Compiling indexmap v1.9.1
Compiling symbol_table v0.2.0
error[E0635]: unknown feature `proc_macro_span_shrink`
--> /home/zane/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pro
c-macro2-1.0.47/src/lib.rs:92:30
|
92 |     feature(proc_macro_span, proc_macro_span_shrink)
|                              ^^^^^^^^^^^^^^^^^^^^^^
For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:21: egg-herbie] Error 101
```
> update cargo.lock file

- src/web/common.rkt
We were using the wrong variable name and that was causing problems.
> Fix crashes in `format-prelude-instruction`

- src/core/reduce.rkt
- src/core/taylor.rkt
- src/syntax/rules.rkt
This PR continues to work on removing unsoundness in Herbie, specifically by fixing `taylor-sqrt` and `taylor-cbrt` to give sensible results for series expansions of functions like `sqrt(x)` and `cbrt(x + x^2)`. However, removing the unsound rules during simplify still hurts performance. My plan is to merge this as is, and work on disabling them later.
> Remove unsound simplify rules

- src/core/egg-herbie.rkt
- src/soundiness.rkt
This PR speeds up the "Soundiness" phase in Herbie that produces the proofs. For example, for quadratic, soundiness goes from ~30% of runtime to ~13%.
The basic optimization is simple. In soundiness, for each simplify or rewrite alt, we construct the start and end expression, re-create the e-graph that it was extracted from, and construct the proof they are equal. The PR just batches these proofs, so that if two proofs are for the same e-graph, the e-graph is grown once and then all proofs for it are extracted one-by-one. This is way faster, because the total number of e-graphs in question is very small—bounded by 8 but often smaller because later iterations often don't generate useful alts.
Note that I don't bother batching, say, evaluating each expression at a point because that's …
> Batch e-graph growing operations to speed up soundiness

- src/patch.rkt
Unable to run the  following CI command.
```
racket infra/ci.rkt --precision binary64 --seed 0 be
nch/hamming/
src/patch.rkt:96:26: *taylor-order-limit*: unbound identifier
in: *taylor-order-limit*
location...:
src/patch.rkt:96:26
```
> Missing config file for ci

- src/errors.rkt
- src/syntax/read.rkt
- src/web/demo.rkt
This PR fixes #731. The issue is this. When the user submits a job through the web demo, we add it to a queue, and then later the worker thread pulls it out of the queue and works on it. But before putting it in the queue, we want to check it for syntax and type errors, so that the user gets fast feedback in that case. We were calling `assert-syntax!` and `assert-program-typed!` to do that, but we weren't running desugaring before type checking, so we were rejecting programs that actually would have worked.
This PR fixes that by using `parse-test` to check for syntax errors, and it also improves error messages in case things don't type check.
> Desugar FPCore entered in the web demo before running it

- infra/testApi.mjs
- src/config.rkt
- src/load-plugin.rkt
- src/platform.rkt
- src/sandbox.rkt
Fixes some bugs introduced by #683.
- `cost` endpoint was broken
- platforms syntax interpreted costs literally rather than binding to a temporary
- current platform gets reloaded every time `run-herbie` is called
> Fix `cost` endpoint and platforms.

- src/compiler.rkt
Recent changes to Rival have broken this rule. But that's because they uncovered a hidden bug: exact constants like `1/3` would be compiled into a point interval `[x, x]`, where `x` is a bigfloat approximation to 1/3. Note that that doesn't actually include 1/3! Rival recently got more precise with intervals like this, and as a result it now correctly reports that `pow` fails on all points in that interval. So this PR fixes the compiler to round each constant both ways and form an interval that way. This might slow Herbie down slightly, but it's probably not a big effect and it's only in bigfloat mode. If this is really a big problem, we could be more clever, like only rounding both ways when `x != float(x) or precision < 53`.
> Fix test failures when trying to test the `pow1/3` rule

- bench/hamming/trigonometry.fpcore
- src/syntax/syntax.rkt
The `tanhf` benchmark has the following benchmark, I think this was added in Herbie Gold: `(and (<= (- INFINITY) x) (<= x INFINITY))`. Besides not really making sense (this is true of literally all values!) it is also invalid in Rival because INFINITY is not a real number. This was causing crashes.
This PR removes the nonsensical precondition and fixes the crashes by making INFINITY denote to an interval (from max-val to infinity).
> Remove a bad precondition from the `tanhf` benchmark

- src/core/regimes.rkt
This PR adds FL type annotations to regimes add-split point function increasing the performance by ~2x over current version.
[Metrics for fl branch](https://nightly.cs.washington.edu/reports/herbie/1710263105:nightly:zane-regimes-fl:fe07cd4dc6/timeline.html)
[Metrics for main](https://nightly.cs.washington.edu/reports/herbie/1710245633:nightly:main:d14d36a196/timeline.html)
> FL type annotations for Regimes

- src/core/localize.rkt
- src/error-table.rkt
- src/mainloop.rkt
- src/sampling.rkt
- src/sandbox.rkt
- src/timeline.rkt
Basically, two of our timeline tables (`outcomes` and `mixsample`) are really really big. So far we've solved that by manually inserting calls to `timeline-compact!`, which reduce the size of the tables by merging duplicate rows. But that doesn't happen if Herbie times out, since then it doesn't do the `timeline-compact!` step either! So this PR adds a list of keys to always compact, so that you don't need to write `timeline-compact!` manually any more.
> Add feature to always compact certain timeline tables

- src/web/history.rkt
This PR changes the location term of the goal proof step from `false` to the empty list `'()`. This functionally changes nothing in Herbie.
When a derivation is described as a list of proof steps, there is always a step with direction "goal" which represents the original expression. Before this PR, this step had a location of `false`.
In every other place where a location is defined, the location is defined as a list. 
Changing this one instance where a location is defined as `false` instead of a list adds consistency by changing the type of `loc` from the sum type `Boolean | Array` to the type `Array`.
> change loc of proof initial 'goal' term to empty list instead of false

- src/mainloop.rkt
- src/sandbox.rkt
This PR basically continues the endless battle to make the mainloop maintainable by splitting the `extract!` function into a few separate functions, and similarly moving Barhgav's explanations to a new `explain!` function. In the process, I managed to add a use of `batch-errors` and rewrite one complicated function into a simpler one.
> Clean up the main loop a bit by splitting things into functions

- src/web/history.rkt
This PR corrects a bug in converting preprocessing information to JSON that caused any run with preprocessing to crash on `herbie web` instances.
The preprocessing operator was represented as a `symbol`, which is unsupported by JSON conversion; this PR converts these symbols to JSON-legal strings.
> Fixed preprocessing JSON conversion

- LICENSE.md
- egg-herbie/info.rkt
- src/compiler.rkt
- src/core/localize.rkt
- src/error-table.rkt
- src/info.rkt
Since literal values now know their own precisions, the `munge` and `all-subexpressions` functions can be simpler.  I think this PR is a small refactor that helps with the long-term goal of moving real computation to Rival.
> Simplify `munge` and `all-subexpressions` by removing type logic

- src/compiler.rkt
- src/ground-truth.rkt
- src/points.rkt
Basically, this PR just switches to using vectors as the output of compiled progs/specs instead of lists. This should reduce allocations, avoid reversing lists, avoid traversing lists, and so on. It should save at least a few minutes. Plus, it turns out that the list in `make-search-func` was not using `in-list` and adding that annotation (now `in-vector`) should be a big speedup on its own.
> Faster `search-func` and `eval` by using vectors

- src/core/bsearch.rkt
- src/ground-truth.rkt
- src/sampling.rkt
- src/searchreals.rkt
- src/syntax/test-rules.rkt
- Don't `analyze` forever we start with lots of hyperrects
- Don't return precision from `ival-eval` (no one uses it)
- Do ival->repr conversion inside `ival-eval` (removes duplication)
- Only check for infinities for `binary64` repr (not sure about this, but it's slow)
> Clean up sampling

- src/patch.rkt
- src/soundiness.rkt
This PR makes a big overhaul of `patch.rkt`:
- Move the "functional" parts into separate functions, so that there are ex. `gen-series` and `gen-series!` functions. (Long term the goal is to get rid of the imperative bits.)
- Split repr-change changes away from rewrite changes
- Remove unused functions
> Simplify `patch.rkt` by making it more functional and splitting out repr changes

- src/compiler.rkt
- src/config.rkt
This branch introduces an optimization for real evaluations. This optimization allows to skip reevaluation of an operation if a) this operation has the same precision as an iteration before b) children of this operation have the same precisions as an iteration before and their children as well (recursion).
> No repeats in tuning

- src/web/demo.rkt
- src/web/pages.rkt
- src/web/thread-pool.rkt
Herbie sometimes crashes when generating a web page. At the moment, that output goes to the console, which isn't really the best option (it's hard to get to on nightly). This PR instead makes it output the error trace to the page it was generating, which maybe also isn't ideal but at least it's easy to find by clicking around.
> Output something when Herbie crashes generating a web page

- src/compiler.rkt
@AYadrov found this very tricky bug in Herbie's register machine compiler. The compiler compiles an expression (like `(+ (* a a) (* a a))`) into a sequence of instructions, like this:
```
; a => 0
(* 0 0) ; => 1
(+ 1 1) ; => 2
```
Note that the `(* a a)` operation ends up de-duplicated and computed only once. However, the instructions don't _actually_ look like that, because the first argument isn't a symbol, it is a function:
```
; a => 0
(#<procedure ival-mult> 0 0) ; => 1
(#<procedure ival-add> 1 1) ; => 2
```
This mostly works fine, but numerical constants don't. A numerical constant like `180` compiles to a zero-argument instruction like `(#<procudure const>)` and that means we make a new constant function that returns 180. However, these instructions now don't compare as equal, …
> Fix duplication bug in register machine by splitting compile & link

- src/core/regimes.rkt
This PR accomplishes the following changes to speed up regimes.
- Invert dependencies of alts and point index in core loop
- reuse vectors avoid allocation
- tie breaking function for when to update best alt
- remove initial and add-splitpoint function calls
- cleans up code to go from vectors to split index list
- comments explaining algorithm
> Faster Regimes

- src/config.rkt
- src/core/localize.rkt
- src/error-table.rkt
- src/mainloop.rkt
The main goal of this PR is to speed up `batch-localize-cost`  by doing more batching. Specifically, right now we call `batch-localize-cost` with five exprs. Then for each one we do a simplify batch. Instead, this PR does one big simplify batch for all five exprs together. This is faster (one batch, not five) and simpler (due to a bit of refactoring).
This PR does a couple of other things, too:
- `batch-localize-errors` now returns a single hash, instead of one hash per input expr. Turns out we didn't need that extra structure, and it was making things messy
- I merged `batch-localize-errors` and `batch-localize-cost`. This isn't strictly necessary but after nightly runs I expect to try using simplified subexprs instead of the original subexprs for localize, which I think will lead to …
> Speed up `batch-localize-cost` with more batching

- src/core/alt-table.rkt
This PR fixes a performance regression introduced in #441, which made the `alt-table-all` a list and thus introduced a repeated list scan, in other words, accidentally quadratic. It's only recently become an issue. (Also as a small thing it adds a type hint to an iterator to make it faster.)
> Trivial speed-ups in `atab-add-altns`

- src/compiler.rkt
This bug was introduced by #774.
This bug loses ~100bits of precision in some cases where it is needed.
The changed line of code checked whether precision increased of an operation before increasing, where new precision was calculated slightly wrong.
As a result, a lot of points spin without converging.
The bug was revealed by analyzing `powComplex, real part` benchmark.
> Backward-pass precision propogation bug

- .github/workflows/distribute.yml
- .github/workflows/plugins.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- .github/workflows/tools.yml
- .github/workflows/unit-test.yml
- src/info.rkt
Merging this PR is one of a couple of steps to get M1 macOS packages working, but this is very exciting!
> Extend the CI to build both `x86` and `arm64` macOS packages

- src/web/timeline.rkt
This got lost during my optimizations to `timeline-start!`
> Change timeline table for sampling to sort by time

- egg-herbie/Cargo.lock
- egg-herbie/Cargo.toml
- egg-herbie/src/math.rs
This PR updates Herbie's egg dependency to a newer version that fixes a long-standing bug in proofs (see egraphs-good/egg#310).
> Fix egg proofs

- src/ground-truth.rkt
- src/sampling.rkt
To be clear, this PR is optimizing the code that *selects a random input*. This is a small fraction of the sampling phase as a whole—something like 15%. My guess is that this optimization speeds up that 15% by about 2×, basically by precomputing the ordinals for each interval's endpoint instead of recomputing them per-sample.
> Faster code for sampling a point

- src/compiler.rkt
- src/correct-round.rkt
This PR keeps `compile-progs` and its dependencies in `compiler.rkt` but moves `compile-specs` and their dependencies into `correct-round.rkt`, with the goal of eventually moving `correct-round.rkt` itself into Rival. To that end, all dependencies in `correct-round.rkt` are explicitly annotated, so that we can work toward eliminating them.
Note that there was some pretty weird stuff around `repr-conv` operators, which I removed and am hoping won't break anything.
> Split the float and interval compilers / interpreters

- src/config.rkt
- src/core/localize.rkt
- src/error-table.rkt
- src/mainloop.rkt
This re-splits `batch-localize-cost` and `batch-localize-error`, adds a timeline break between them (`-costs` is now a `simplify` phase, which I think is fair), and makes them each togglable with flags.
> Clean up `localize`

- www/doc/2.0/api-endpoints.html
Before we had a cost endpoint, but it was not documented. This PR adds documentation regarding inputs and outputs, including types and specific examples. 
Pictures:
> Added documentation of the /cost API endpoint

- src/web/common.rkt
Quick fix for a bug in `render-fpcore` which breaks the cost script.
> Quick fix `render-fpcore`

- src/accelerator.rkt
Adds an error message for register-accelerator-impl if the impl does not have the right arity.
> Add arity error message for register-accelerator-impl

- src/compiler.rkt
- src/core/egg-herbie.rkt
- src/platform.rkt
- src/platforms/avx.rkt
- src/preprocess.rkt
This PR allows platforms to specify an alternative `if` cost: the cost of an `if` is the sum of the condition, if-true, and if-false branches, plus some constant value. This is likely useful for vectorized code.
> Alternative `if` cost method

- infra/diff.rkt
This is a simple PR that was meant to be added to the previous Report one.
Its main goal is to print the data file when the Determinism test fails.
Despite trying to recreate it locally, the tests don’t fail, but seemingly fails in the CI tests sometimes. This would better help us understand the source of the error.
> Printing data file when Determinism Test fails

- src/web/demo.rkt
This PR fixes a subtle bug in `generate-report` where it is currently generating URL's like the following. 
`#<procedure:hash>.3d2f9b2771597ba020e32683e23e5e8fb9fe5752` 
where it should be generating something like. 
`6a7e2826cc8869174e6755073c26ecbd069c8ff6.3d2f9b2771597ba020e32683e23e5e8fb9fe5752`
> Fix url for generate-report

- src/.#explain.rkt
- src/core/localize.rkt
- src/explain.rkt
- src/mainloop.rkt
This pull requests splits the main explanation function into three sub-functions with the eventual goal of exposing the explanation functionality as an endpoint for external use independent to other parts of Herbie(like Odyssey).
> Split the explanations function

- src/config.rkt
- src/sandbox.rkt
This PR just moves the globals from Sandbox.rkt to Config.rkt to consolidate globals into one place.
> Move sanbox.rkt globals to config.rkt

- src/correct-round.rkt
- src/ground-truth.rkt
- src/sampling.rkt
This PR continues the project of separating the sampling code from Herbie by making the `rival-machine` struct private.
The mechanism is pretty simple; the compiler now supports `assert` so instead of feeding in the precondition as `foo` we now feed it in as `(assert foo)`. If the precondition is ever false, then evaluating it will now error, which will make the point exit early as `invalid`.
> Hide `rival-machine` implementation details from the rest of Herbie

- src/correct-round.rkt
- src/ground-truth.rkt
- src/sampling.rkt
- src/searchreals.rkt
This PR prepares for adding sampling code into Rival, in a few ways:
- It fixes all extant bugs and warnings
- It renames all of Herbie's sampling code identifiers to not conflict.
I've tested this code to work even when the updated Rival code is installed.
> Prepare for removal of sampling code

- infra/testApi.mjs
Improving `infra/testApi.mjs` to have a little more organize and robust API testing as the API surface of Herbie grows.
- Deduplicate formulas
- Reorganize the file order by API being tested at that point in the file.
- Add at least one test for each API
Future PR:
- More and better robust testing (open to suggestions)
- Concurrent testing of `improve-start` and `check-status`
> Improve Herbie API endpoint testing

- infra/ci.rkt
- src/sandbox.rkt
- src/web/demo.rkt
- src/web/make-graph.rkt
- src/web/pages.rkt
- src/web/traceback.rkt
This PR re-merges changes from #825 that were missed from chained merges.
Also fixes bug for jobs with the same `hash`/`job-id` but different commands used.
> Fix job-id collision

- src/searchreals.rkt
- src/syntax/rules.rkt
I updated Rival to no longer provide "explanations" for domain errors; Herbie needs some changes (simplifications) to handle this correctly.
> Fix Rival bindings

- src/timeline.rkt
- src/web/timeline.rkt
This PR tracks live and allocated memory at the end of each phase, and shows the results in the timeline:
The hope is that, if we lower memory usage, we'll have fewer garbage collections, which will lead both to faster code and also to fewer synchronizations in multithreaded code so more parallelism.
> Track memory usage per-phase

- src/web/make-report.rkt
- src/web/resources/report-page.js
This PR fixes #730, or at least, as close to fixing as we're going to get. Basically, if you generate a report in Herbie and double-click on the resulting file, nothing shows up. That's because when you just double-click on a file, it opens it in your browser with a `file://` URL, and those are heavily limited by browsers.[1] We can't exactly fix this [2] but we can show a nice error message and teach users to avoid this error, which is what this PR does. The resulting page looks like this:
One nicety is that the Python command automatically subs in the right path because we can get it from the `file://` URL. It also switches to Windows paths for Windows machines.
[1] I do not agree with this decision, even after investigating the reasons, but it is now standard so hard to change.
[2] One …
> Help users with local reports

- src/syntax/read.rkt
- src/syntax/type-check.rkt
- src/web/thread-pool.rkt
Passed in precision instead of representation to store racket expressions. Pushed *functions* hash table to thread workers such that user-defined functions are defined in the table in all threads and are able to be expanded.
> Fixing User Defined Function (Modulus) Bug

- src/datafile.rkt
- src/sandbox.rkt
- src/web/resources/report-page.js
This PR adds a dropdown that filters the report to certain warnings:
I think this makes warnings more useful to use developers, which is nice.
This PR also refactors the dropdown to filter by suite—I used it as a model and eventually found a nicer way to do it.
> Allow filtering the report by warning

- src/web/demo.rkt
- src/web/server.rkt
This PR cleanly separates the `job-server` abstraction from the current `demo` abstractions by moving them into their own file. Decoupling this code sets us up for allowing multiple threads to perform work instead of just one `worker-thread` and its associated job queue.
> Job server public API introduction.

- infra/testApi.mjs
- src/web/demo.rkt
This PR adds the `x-herbie-job-id` header to the response of the API endpoints that have associated `job-id`s. This allows the client to make additional queries about the job after the initial request is made as long as the same server instance is running. 
This might also make it easier for Oddessy to experiment and patiently migrate to an async version of the current APIs if needed.
This is just an addition to the current API surface. The downside of exposing the `job-id`s is that they are only valid well that instance of the server that generated the `job-id` is still running. Further modifications could be made to write the cached data to disk and query there if the data is not found in memory from the server restarting for some reason.
Partial example of the server response.
```json …
```
> Add job-id to response headers.

- src/core/egg-herbie.rkt
- src/core/localize.rkt
- src/core/rr.rkt
- src/core/simplify.rkt
- src/mainloop.rkt
- src/patch.rkt
- src/preprocess.rkt
- src/soundiness.rkt
Refactors the `egg-herbie` interface. Only two functions are important.
`make-egg-runner(exprs, reprs, schedule)` (previously `make-egg-query`):
- takes a list of exprs (and output reprs) and a rule "schedule"
- the egg runner specifies how to  _reproducibly_  run egg for a set of expressions
`run-egg(runner, cmd)`:
- actually creates an e-graph and runs the rule schedule and then performs an "extraction"
- an extraction is one of single-expression extraction, multi-expression extraction, or proofs
- importantly expression extraction is not run when finding proofs
- future work: preprocess only needs to check if expressions are in the same e-class
Hoping for a performance boost. This PR is a follow-up to #875 .
> Optimize `run-egg` to only do necessary work

- src/mainloop.rkt
I noticed well trying to understand `run-improve` and that the argument count at this call site doesn't match the signature.
This might be worth keeping around for a section of the code I don't know about.
> Remove unused improve function

- src/core/regimes.rkt
After running Nightly  the time of Regimes-Speedup was 91.2 min while main was 91.5 min. While make-regime! that contains pareto-regimes takes 1012.34s in Regimes-Speedup, in main it takes 1073.72s. During profiling there is much more time spent in pareto-regimes since the exprs-to-branch-on is now being calculated during this function. This makes pareto-Regimes take 30.55s in Regimes-Speedup but only takes 12.74s in main. I'm unsure where exactly the speedup can be found in the profiling but it is faster I think.
> Regimes speedup

- src/syntax/test-rules.rkt
This PR fixes #878. The `pow-pow` rule is not actually sound if `a < 0`, `b*c` is odd, and one of `b` or `c` is even.
> Fix `pow-pow` rule failures in CI

- infra/nightly.sh
- infra/run.sh
Attempting to force exit run.sh script when a run on a specific benchmark suite fails such that merge-datafiles does not run when there is a segfault crash. Only publishing the results if run.sh succeeded.
> Merge-Datafiles Crash Fix

- src/web/server.rkt
This PR changes the printed output of jobs to only display the name of the test not the entire test for cleaner terminal output.
before:
```
Improve Job improve started:
b476925bc3c1474f6b20181eec4414df3e795cb4 #s(test sqrt(x + 1) - sqrt(x) #f (x) (-.f64 (sqrt.f64 (+.f64 x #s(literal 1 binary64))) (sqrt.f64 x)) () #t (-.f64 (sqrt.f64 (+.f64 x #s(literal 1 binary64))) (sqrt.f64 x)) (and (<=.f64 #s(literal 0 binary64) x) (<=.f64 x #s(literal 178999999999999996376899522972626047077637637819240219954027593177370961667659291027329061638406108931437333529420935752785895444161234074984843178962619172326295244262722141766382622299223626438470088150218987997954747866198184686628013966119769261150988554952970462018533787926725176560021258785656871583744 binary64))) () binary64 ((x . binary64)))... …
```
> Only print test name

- src/sandbox.rkt
We were wrapping things in unnecessary lists due to a change in the internal presentation of things.
> Handle `:alt` output correctly in Herbie's FPCore output

- src/web/demo.rkt
If `--save-session` is enabled, Herbie will try to generate pages even for invalid job IDs, which will then crash. Kind of no harm no foul but better to fix it than not.
> Fixed a bug related to handling invalid job IDs when `--save-session` is enabled

- Makefile
This PR adjusts the `make install` command to also update the `rival` package to help keep dependencies in sync.
> Add update rival to make install command

- infra/testApi.mjs
- src/api/demo.rkt
- src/api/server.rkt
This PR adds the commit hash to reconstruct the graph.html links for Odesssy to link to.
Adds missing `Access-Control-Allow-Origin` header to the `timeline` API.
> Add commit hash and Access-Control-Allow-Origin for Odyssey

- Makefile
Not sure why `--auto` works in this case, but the `raco pkg update rival` command doesn't work by default if it's a linked repository.
> Fix nightly somehow

- egg-herbie/main.rkt
- src/core/egg-herbie.rkt
- src/core/preprocess.rkt
This PR changes symmetry finding in preprocessing and fixes an FFI bug.
- symmetry: check if two expressions have the same e-classes rather than if they have the same extracted expression. 
- FFI bugfix: use `_stdbool` rather than `_bool` since Rust seems to adhere to `_stdbool`.
> Better preprocessing

- .github/workflows/unit-test.yml
- Makefile
- src/api/datafile.rkt
- src/api/demo.rkt
- src/api/server.rkt
- src/core/bsearch.rkt
- src/core/egg-herbie.rkt
- src/core/preprocess.rkt
- src/core/reduce.rkt
- src/core/test-rules.rkt
- src/syntax/platform.rkt
- src/syntax/sugar.rkt
- src/syntax/syntax.rkt
Unfortunately, globstar `**` is not universal in all shells. Changes the `raco fmt` compliance check from `raco fmt -i **/*.rkt` to `raco fmt -i $(find . -name '*.rkt')`. Added a `make fmt` rules to handle this.
> Fix `raco fmt` check

- .fmt.rkt
- src/syntax/syntax.rkt
Removes the `ival` field for operators and adds a few unit tests. Adds formatting for a new macro.
> Remove `ival` field of operators

- .github/workflows/distribute.yml
Fixes crash in CI stemming from dependency caching. Removed `~/.cargo/bin` from cached paths since these are the executables that are downloaded when installing Rust.
> CI: fix dependency caching

- infra/testApi.mjs
- src/core/points.rkt
This PR fixes a bug where `/localerror` jobs were be incorrectly hashed for job ids causing two request for the same formula but different points to serve what ever response was made first.
> Fix local error job id hashing

- egg-herbie/main.rkt
- egg-herbie/src/lib.rs
- src/core/compiler.rkt
- src/core/egg-herbie.rkt
- src/core/localize.rkt
- src/core/mainloop.rkt
- src/core/patch.rkt
- src/core/programs.rkt
- src/core/soundiness.rkt
- src/reports/common.rkt
- src/reports/history.rkt
- src/reports/pages.rkt
- src/syntax/platform.rkt
- src/syntax/sugar.rkt
- src/syntax/syntax.rkt
This PR adds "approx" nodes to track arbitrary approximations, e.g., polynomial approximations, within floating-point programs. An approx node `(approx s e)` consists of a spec `s` and a program `e` where `(prog->spec (approx s e))` is `s` and `(eval (approx s e))` is equivalent to `(eval e)`.
> Approx nodes

- src/config.rkt
It turns out that `.git` can be a file (this is called a "gitlink") and in that case we still need to call `git` to get the current branch.
> Fix branch name on nightly

- infra/testApi.mjs
- src/api/demo.rkt
- src/api/sandbox.rkt
- src/api/server.rkt
The changes in this branch will now allow user to get error explanations data at "/api/explanations". Earlier we didn't had any api to fetch sorted explanations table of explain.rkt . Now we can fetch that data through a fetch api call to "api/explanations". I have created a new branch from main and added all my changes here so it is easy and simple to merge.
> Error Explanations API added

- src/api/demo.rkt
This PR enables timeline profiling for all API endpoints. This allows Odyssey to open `/timeline.html` links using the `path` parameter sent over with the majority of API request. 
Note that profiling is still disabled `#:profile? #f` for most of these endpoints so maybe worth enabling or change how the `timeline.html` page renders with no profiling enabled is appropriate.
> Enable timeline for `/cost` and `/alternatives` endpoints.

- src/api/sandbox.rkt
- src/utils/timeline.rkt
This PR fixes an invariant in `timeline` pointed out by @pavpanchekha  well we were working on #940. 
When enabling `timeline` on commands that don't actually submit any timeline events like `'sample` for example. This would cause the following crash to happen when `(timeline-event! 'end)` fires after the command is run. 
```
car: contract violation
expected: pair?
given: '()
```
At: `timeline.rkt` ~ line 36
```
(define (timeline-event! type)
(when *timeline-active-key*
(hash-update! (car (unbox (*timeline*)))
*timeline-active-key*
(curry append *timeline-active-value*)
'())
(set! *timeline-active-key* #f))
```
This PR fixes that in two ways. Propagating a less opaque error message `'timeline "Cannot push to an empty timeline"` as well as pushing a `'start` event on the timeline before …
> Throw `error` when attempting to push to an empty timeline.

- src/api/sandbox.rkt
- src/config.rkt
- src/core/bsearch.rkt
- src/core/egg-herbie.rkt
- src/core/mainloop.rkt
- src/core/patch.rkt
- src/core/reduce.rkt
- src/core/taylor.rkt
- src/syntax/platform.rkt
- src/utils/errors.rkt
- src/utils/timeline.rkt
We use the "reset" mechanism to flush caches between benchmarks (to make sure we don't unfairly credit one benchmark for work done in another). Over time the reset mechanism accumulated various hacks; there are separate "initialize", "reset", and "finalize" methods, and resetters have priorities. But we don't use any of these features!
This PR basically throws away all the gunk and, in the process, simplifies the syntax a bit. You now write:
```
(define/reset *foo* val)
```
This then re-evaluates `val` when it needs to be reset. Order of resets no longer guaranteed.
> Simplify the "reset" mechanism

- src/reports/make-graph.rkt
- src/reports/pages.rkt
This PR fixes a bug when trying to view the `graph.html` page for example an `/alternatives` request from Odyessy. Currently `make-graph` only supports `'improve` commands. I think some sort of result page could be made for the other commands though I think Odyessy might be a better route here.
> Fix graph.html page not being available for all commands.

- src/api/sandbox.rkt
- src/core/explain.rkt
- src/core/mainloop.rkt
For mysterious reasons, the Herbie `mainloop.rkt` stores all of its state in a single global struct instead of multiple variables. This seems to carry no benefits whatsoever, since we never make copies of the struct and probably won't. (Maybe this all goes back to the Herbie visualizer?) Anyway, removing this struct and the related code makes the file easier to read with basically no downsides.
Besides this one change it inlines a bunch of code in `mainloop.rkt` to try to simplify that file.
> Remove the `shellstate` struct

- src/config.rkt
- src/utils/timeline.rkt
Extends `define/reset` to support a manual reset. By default,
```
(define/reset name value)
```
installs a resetter that sets the parameter `name` to `value`. The timeline is the only resettable parameter where we want to keep the current value of the parameter, which is a box, but mutate the value in the box. For this, the option
```
(define/reset name value reset-fn)
```
has been added and the timeline parameter is now defined as
```
(define/reset *timeline* (box '()) (lambda () (set-box! (*timeline*) '())))
```
> Add manual resetter for `define/reset`

- src/api/sandbox.rkt
- src/api/server.rkt
- src/reports/pages.rkt
- src/reports/traceback.rkt
- src/utils/errors.rkt
This PR restores rendering of exceptions in reports. To get exceptions through the new server design, exceptions are unpacked into s-expressions that contain enough information for rendering.
> Render exceptions in reports

- src/api/demo.rkt
- src/main.rkt
- www/doc/2.1/options.html
This PR adds a `--no-browser` flag to the web demo. Which disables the default browser from being opened and has no other side effects like `--quite`.
Motivation:
When personally working on Herbie I prefer to use Firefox or Brave well my default browser is set to Safari for personal reasons. I used to use `--quite` but this disables most output which I find unhelpful as I can't distinguish whether the server has started or racket is still compiling Herbie. I also prefer to have all output logged when working on Herbie to understand what path was taken through the code base.
Currently, I have been manually setting `#:launch-browser?` in `run.rkt` to `#f` but I often forget to leave this out of commits. I would very much appreciate a flag to do this for me.
> Add --no-browser flag.

- src/api/server.rkt
- src/reports/make-graph.rkt
This PR fixes a bug where `graph.html` would only render the first two alts due to an error in my logic for generating `history` in `server.rkt`.
When running the demo for the default `sqrt(x + 1) - sqrt(x)` Accuracy vs Speed display 9 `alts` available but when you scroll down only the first two `alts` are displayed.
> Fix pcontext bug in rendering alternatives for `graph.html`

- egg-herbie/main.rkt
- egg-herbie/src/lib.rs
- src/core/egg-herbie.rkt
This PR moves all unsafe FFI code into the `egg-herbie` package and makes a number of improvements. It adds three new FFI types to convert between Rust strings and Racket data more efficiently. In addition, the `egg-herbie` interface accepts Racket data rather than strings.
| Name             | Racket type  | Rust type          |
| --------------  | -------------- |----------------- |
| `_rust/string`  | `string?`         | `*const c_char`  | 
| `_rust/datum` | `any/c`           | `*const c_char`  |
| `_rust/data`    | `(listof any/c)` | `*const c_char`  |
Rust-to-Racket: converts to a Racket string by first copying the string to a Racket byte string and then converting to a Racket string using `byte->string/utf-8`. Racket-to-Rust: converts to a byte string using `string->bytes/utf-8` and …
> New egg-herbie interface

- src/api/demo.rkt
This PR fixes an [Issue](https://github.com/herbie-fp/odyssey/issues/94) in Odyessy. Which causes submitting the det44 benchmark to fail with `Connection error: read-bindings: body length exceeds limit`. 
I have bumped the [max body size ](https://docs.racket-lang.org/web-server-internal/dispatch-server-unit.html#%28def._%28%28lib._web-server%2Fsafety-limits..rkt%29._safety-limits~3f%29%29)to 5mb. I don't know if this is a good long-term decision but it allows Odyessy to work on expressions like det44 which uses 3.3mb for a `/alternatives` request.
> Fix body limit for det44 benchmark.

- egg-herbie/main.rkt
- egg-herbie/src/lib.rs
- infra/convert-demo.rkt
- src/core/egg-herbie.rkt
- src/reports/plot.rkt
- src/syntax/types.rkt
This PR primarily contributes a new e-graph serialization method. Rather than serialize the entire e-graph as a string, the new strategy is to first extract the e-class ids in a `u32vector`. Then we iterate through each e-class id and serialize the e-class itself where
```
<eclass> ::= #(<enode> ...)
<enode> ::= <symbol>
| <number>
| (<symbol> . <u32vector>)
```
Overall, the idea is to have less allocation, at any given time, and less pointer chasing, overall. Local testing using Hamming shows that serialization time decreased from ~90 seconds to ~40 seconds. Across the benchmark suite, `egg-herbie` takes about 30% of total run time.
The PR also includes other small changes for performance, cleanliness, or profiling reasons.
> Faster e-graph serialization strategy and refactors

- src/core/localize.rkt
In days of old, `compute-local-errors` used a hash table to store local error lists; this is wasteful and slow. This PR replaces it with a vector, which should be a lot faster.
> Remove the hash table from inside `compute-local-errors`

- src/core/egg-herbie.rkt
This PR switches the `lookup-id` function from a hash table to a vector, which reduces its runtime by about 4x. Overall impact is still small (1 minute maybe? less that variability) but whatever, let's just try to do many small optimizations.
> Faster `lookup-id`

- infra/convert-demo.rkt
- src/api/sandbox.rkt
- src/api/server.rkt
- src/reports/make-graph.rkt
- src/reports/plot.rkt
- src/syntax/types.rkt
This PR fixes a misuse of the `parse-test` function that I introduced when adding more concurrency to Herbie with the new server implementation. This surfaced as a false positive `Warning: unused variable x` when running herbie on the expression `sqrt(x + 1) - sqrt(x)`. Thanks to @bksaiki for pointing out this bug.
Note:
- An update to `fmt` on CI so some formatting changes are also included in the diff.
- Clean up of a few unused variables and imports that I noticed well working on this.
> Fix `Warning: unused variable x`.

- src/core/alt-table.rkt
In a recent PR, the `alt` struct was marked as `#:prefab`. This had the unfortunately side effect of changing `equal?` to be a recursive operation on `alt` instances. This change just makes sure we use `eq?` based tables when we want them.
> Prune explicitly uses `eq?`-based hash tables when alternatives are keys

- src/api/demo.rkt
- src/api/server.rkt
This PR returns previewing the current state of the job view the *time-line* box.
This is done by letting the worker manage a [thread](https://docs.racket-lang.org/reference/threads.html#%28def._%28%28quote._~23~25kernel%29._thread%29%29) to manage which allows us to observe/read the timeline for a given a job. The simplest value of this is the web demo can now display the current state of the job as it did before the use of places.
> Add `check-status` back.

- infra/merge.rkt
- src/api/demo.rkt
- src/api/run.rkt
- src/api/server.rkt
- src/reports/make-graph.rkt
- src/reports/pages.rkt
- src/reports/plot.rkt
- src/reports/timeline.rkt
- src/reports/traceback.rkt
This PR is one part of an idk how many PRs at this point aiming to clean up the `/api` and server (concurrency) abstraction. High-level goals are to deduplicate code and move code that IMO should be "inside" the server isolation and reduce the amount of code transforming data types like `result-hash` and `table-row` which are from previous parallelism abstractions. I also need to add in a method when using Herbie with a single thread to not use `place` as I guess this makes debugging the FFI layer between egg and Herbie more difficult which is why the `reports` part of Herbie does not use the new `sever` abstraction as mentioned by @pavpanchekha in this [PR](https://github.com/herbie-fp/herbie/pull/963#pullrequestreview-2249150505).
This PR reshapes how `make-page` works for writing data …
> Server clean up, Part 1

- src/core/batch.rkt
- src/core/compiler.rkt
- src/core/localize.rkt
- src/core/taylor.rkt
This PR introduces a couple of simplifications / changes / abstractions for batches.
First, there are now `mutable-batch` objects. These are basically the core of `progs→batch`, but turned into a separate mutable object. Concretely, a `mutable-batch` is a hash table (from node to index) plus a list of nodes in reverse order. (It also stores the vars, in reverse order, for the same reason (if any) as regular batches.) You can convert a mutable batch into an immutable one, though you need to supply a rootvec.
Second, there are now `batchref` objects. This just stores a batch and an index, and you can unfold it one step with `deref`. These aren't yet super important, but they're used in...
Third, there's now a `batch-replace` function. This function takes a callback that outputs expressions, …
> New `batch` abstractions

- src/core/alt-table.rkt
- src/utils/pareto.rkt
Adds two optimizations to the alt table:
- `point->alt` map is a vector from index (in the pcontext) to alt since the number of points is fixed
- deduplication when updating Pareto frontiers
> More prune optimizations

- bench/graphics/log-transform.fpcore
This PR adds a new benchmark to get a graphics suit of Herbie. This benchmark is motivated by the Image Processing domain of computer science. This Log Transform is used to bring out detail in dark parts of images.
Credit to Professor Elhabian for the example.
> Add new benchmark for log transform.

- src/core/egg-herbie.rkt
This PR just removes the code that records how many times each rule was applied. This data was basically always useless and it turns out to take a surprisingly long time to actually, you know, run.
> Tiny e-graph speedups

- src/api/demo.rkt
This PR adds CORS headers to the `checkstatus` API to allow Odyessy to start calling the new Async API's.
> Add CORS headers to checkstatus API

- src/core/batch.rkt
- src/core/egg-herbie.rkt
- src/core/localize.rkt
- src/core/mainloop.rkt
- src/core/patch.rkt
- src/core/preprocess.rkt
- src/core/programs.rkt
- src/core/simplify.rkt
- src/core/taylor.rkt
This PR introduces new changes to `egg-herbie` pipeline.
Particularly speaking, `batch`-type input has been implemented for `egg`.
The reason behind this change is: 
Previously, `egg` received a `listof Expr` as an input for `egraph`. These expressions were converted to `batch` structure using internal `egraph` functions (`egraph_add_enode`).
We have noticed that this conversion from `listof Expr` to `batch-egraph` is redundant as we are planning to switch to `batch` structure for expressions inside Herbie.
Instead of doing what is described above, we convert this `listof Expr` to a `batch` on Herbie side and pass nodes to `egraph`.
The new strategy brings some speedup at `egraph-add-exprs` (370s -> 258s) and some slowdown on conversions from `progs->batch` (159s -> 210s). In addition, …
> Batch-input to egg

- src/api/sandbox.rkt
- src/api/server.rkt
- src/core/explain.rkt
- src/core/localize.rkt
This PR adds the exact error info to the `localerror` endpoint. Resulting in the JSON result looking similar to the following. Being an addition to the current JSON and not breaking the structure in which Odyessy knows how to consume. 
Testing locally Odyessy looks to function as normal with this additional information being added.
```json
{
'avg-error': '0.0',
children: [
{
'avg-error': '0',
children: [Array],
e: '+',
'exact-error': '+nan.0'
}
```
`+nan.0` is interpreted as undefined on the Odyessy side and is filtered out in this Odyessy [PR](https://github.com/herbie-fp/odyssey/pull/118) as there is no error here or maybe this should just be 0 like `avg-error` is?
Side effects: 
- I have consolidated where and how the local-error tree is constructed as it was currently being split …
> Surface `exact errors` for Odyssey to consume.

- src/reports/resources/demo.js
This PR fixes the current job count not being updated from the `check-status` request in `--demo` mode.
> Fix stale job count well in demo mode.

- src/api/sandbox.rkt
The Racket `profile` library has an accidentally-quadratic topological sort algorithm, which causes all of our timeouts. Obviously the idea fix would be to make it faster, which might be possible, but until then we can fix all of our timeouts by just running the sampler less often, which produces fewer samples and therefore avoids the bad case in topological sort.
> Do less profiling because the profiler is slow

- src/core/patch.rkt
This branch is built on top of #990. 
The addition on this branch is: removing duplicates in alternatives after taylor expansions and once all the rewritings are done.
Particularly speaking, at the `generate-candidates` function `remove-duplicates` is introduced. 
And since all the rewrites are stored as a `batchref` - we can easily figure out duplicates just by analyzing `batchref-idx` - the parent node a batchref refers to.
The update introduces ~11 mins of speedup.
> Removing duplicates in alternatives

- .github/workflows/resyntax-autofixer.rkt
As discussed at RacketCon, this pull request adds the Resyntax Autofixer workflow to this repository. Once a week, this workflow will run Resyntax on the repository. Resyntax selects a small handful of suggested fixes and puts them into a new pull request. Configurable limits are placed on the number of fixes applied, how many files are touched, and the size of the pull request. I've set those limits quite low to start but feel free to change them to whatever suits your process.
You'll also need to add a secret named `RESYNTAX_APP_PRIVATE_KEY` to the repository. I can send you a key out-of-band.
> Add Resyntax Autofixer workflow

- src/platforms/default.rkt
- src/platforms/fallback.rkt
- src/syntax/platform.rkt
Adding a check when adding identities to make sure implementations in lhs and rhs expressions are supported by the platform. Also fixed a syntax/naming issue with fallback operators.
> CI + Impl Naming Fix

- src/core/egglog-herbie.rkt
- src/core/patch.rkt
- src/core/preprocess.rkt
- src/core/simplify.rkt
- src/core/soundiness.rkt
**Description:**
This PR splits the `run-egglog` interface into 4 parts.
The main goal is to simplify the API and not be dependent on matching the `cmd` argument, but calling the ideal method for getting back the output.
Updates are also made across different files `patch.rkt`, `simplify.rkt`, `soundiness.rkt`, `preprocess.rkt`.
> Splitting the Egglog Herbie Interface

- infra/testApi.mjs
- src/api/demo.rkt
This PR fixes #1030, which was caused by a `timeline` of `#f`. I'm not sure when this case happens, @zaneenders perhaps you know.
> Don't output any timeline information for an empty timeline

- src/core/localize.rkt
- src/core/mainloop.rkt
The `cost-opportunity` heuristic uses the cost model in two ways. First, the cost model is passed to the egraph to find the simplest form of any given expression. And then, the cost model is used again to compute cost opportunity.
The bug is that we were using different cost models for these two phases; default cost model for building the egraph and platform cost model for computing cost opportunity. This lead to weird stuff like the cost opportunity of a node being negative.
The fix is to use the same cost model for both phases; the code does that though note that it is a little ugly in that it duplicates some existing code.
> Use the same cost model throughout `cost-opportunity`

- src/syntax/sugar.rkt
This PR fixes #1019. Looks like we handled null annotations correctly in one code path but not in another.
> Fix null annotations `(! expr)` in desugaring

- src/reports/make-graph.rkt
The functions aren't called, and the definition is just inlined.
> Delete some dead code

- bench/mathematics/logistic-regression.fpcore
When running Herbie benchmarks through Odyssey's FPCore input I noticed this expression has an extra variable.
Issue  #1041
> Remove extra variable y.

- infra/testApi.mjs
- src/api/sandbox.rkt
- src/core/explain.rkt
- src/core/localize.rkt
- src/syntax/types.rkt
Updates the Local Error endpoint to include more information for Odyssey to consume. This PR also splits the code path away from `compute-local-errors` consumed by the core of Herbie. The current implementation is incomplete and incorrect so this PR aims to correct and improve on the current version both in correctness and surfacing more useful information. 
Local error tree nodes include
- average error: `(format-bits (errors-score ulp-error))`
- exact value: Computed against the spec of the node, using `eval-progs-real`.
- actual value: Computed against the program, using `compile-progs`.
- absolute error: Distance between the `exact` and the `actual` value `| actual - exact |`.
- ulps of error: Uses existing code from `compute-local-errors`.
For Odyssey to consume this new API it needs …
> Concrete Values for Odyssey

- infra/testApi.mjs
Like it says in the title, Rival now works on one of the unit test examples
> Fix localerror tests now that herbie-fp/rival#83 is in

- infra/testApi.mjs
- src/api/server.rkt
This PR builds on top of #1027 and adds a "no place mode". Which is set to the default way to run Herbie. As Pavel points out this mode is useful for debugging as `place` adds extra complexity. This mode is required before we can use the server to replace `thread-pool.rkt` which reports uses as its method of calling `run-herbie`.
This PR is also a replacement for the previous attempt #995.
> Server "no place mode"

- infra/testApi.mjs
- src/core/localize.rkt
This PR removes some hacks obsoleted by herbie-fp/rival#83 and also cleans up the code in various minor ways.
> Further clean up `localize.rkt`

- src/api/sandbox.rkt
This PR fixes this potential bug by using one of Herbie's globals instead of hard coding the value 256.
> Fix potential bug in `sandbox.rkt`

- src/core/rules.rkt
Description:
This PR introduces the implementation of all inverse rules. The inverse rules allow the system to reverse operations in order to achieve a few goals. One goal is by adding inverse rules we hope to prove more expressions equal to one another so that they are in the same eclass. We also hope to further improve results as the quality of our rulesets improve with missing rules. There were previous issues due to a bug with using the default cost model but after that was fixed we now have better results
> Update rules.rkt to include inverses.

- src/api/improve.rkt
This PR moves the `improve` command over to using `server.rkt` as a step towards removing `thread-pool.rkt`.
> Use server for `improve` command.

- src/reports/resources/report-page.js
This PR reverts one of the changes from #1060 that resulted in the NaN% bug above.
[Current Nightly](https://nightly.cs.washington.edu/reports/herbie/1732447436:nightly:main:c2c6fd5ab9/)
[After change](https://nightly.cs.washington.edu/reports/herbie/1732553559:nightly:zane-revert-report-js:d153e0945a/)
> Revert change to report-page for NaN% bug.

- egg-herbie/main.rkt
- infra/nightly.sh
- infra/run.sh
- src/api/sandbox.rkt
- src/core/bsearch.rkt
- src/core/mainloop.rkt
- src/core/patch.rkt
- src/core/preprocess.rkt
- src/core/programs.rkt
- src/core/regimes.rkt
- src/core/sampling.rkt
- src/core/simplify.rkt
- src/syntax/platform.rkt
- src/syntax/sugar.rkt
- src/syntax/syntax-check.rkt
- src/syntax/syntax.rkt
- src/syntax/type-check.rkt
- src/utils/errors.rkt
This PR includes:
- Replace `string-join` to `string-append` with constant inputs.
- Bump nightly to six-way parallelism (tried 12, didn't help, confusing)
- Delete dead code in `regimes.rkt`; also remove duplicate of `all-subexpressions`
- Simplify the reconstruction step in `err-lsts->split-indices`; also rename to `infer-split-indices`
- Remove `operator-deprecated?` on account of no operators are actually deprecated
- Remove dead / unused code in `syntax.rkt`
- Remove the ability to disable warnings (never used)
> Ongoing cleanup PR, merged intermittently

- src/reports/resources/report-page.js
This PR adds a new report page feature: mutli-pareto plots when in diff mode. Here's an example with the current and baseline `hamming` results:
The XY plot has a similar (though uglier) feature. There are also some minor code tweaks.
> Report page tweaks

- src/core/derivations.rkt
- src/core/mainloop.rkt
- src/core/patch.rkt
- src/core/preprocess.rkt
- src/core/soundiness.rkt
- src/reports/history.rkt
- src/reports/resources/report.css
This PR removes the part of Herbie that evaluates each intermediate rewrite step in a derivation. This data isn't really used anywhere by anyone, it costs time (not a lot in regular Herbie, but possibly a lot in custom platforms), and it's code we carry around for no reason.
> Remove the "soundiness" step

- infra/ci.rkt
- infra/testApi.mjs
- src/api/run.rkt
- src/api/sandbox.rkt
- src/api/server.rkt
- src/reports/pages.rkt
Previous PR #1064 inadvertently disabled profiling, as noted in #1078. Worse, the way profiles worked _before_ that PR was pretty weird and wouldn't be compatible with the `server.rkt` approach. This PR fixes everything by making profiles yet another entry in the `job-result` struct and re-enabling them for nightlies.
> Re-enable profiles on nightly runs, and redo profiles in general

- src/platforms/binary32.rkt
This PR fixes a tiny oversight in Herbie that actually lead to non-determinism. Basically, when we load `fma.f32` over FFI we load `fma` instead of `fmaf`, but we still give it the correct type signature. I'm not even 100% sure what this actually leads to specifically (reading junk out of unused vector lanes?) but here we are.
This is somehow the root cause of the non-determinism. FML.
> Fix non-determinism

- src/reports/timeline.rkt
- src/utils/timeline.rkt
This PR records time spent GCing in each phase. The idea is that we can use this to determine how big a fraction of runtime GC is, to confirm our hypothesis that it's a big fraction.
> Measure and report GC time

- src/api/datafile.rkt
- src/api/run.rkt
- src/main.rkt
This PR removes `herbie diff` and its supporting code. Back in the day this was a command-line way to diff reports, but these days that's built in to the JS of the report page and this code is no longer needed.
> Remove `diff-report` and friends

- src/api/demo.rkt
- src/api/improve.rkt
- src/api/run.rkt
- src/api/server.rkt
Every single call to `create-job` immediately passes the created command to `start-job`, so this PR merges the two.
> Merge `create-job` and `start-job`

- infra/index.css
- infra/make-index.rkt
- infra/merge.rkt
- infra/nightly.sh
- infra/regression-chart.js
- src/api/datafile.rkt
- src/api/demo.rkt
- src/api/run.rkt
- src/api/server.rkt
- src/main.rkt
- src/reports/resources/report-page.js
- src/reports/timeline.rkt
This PR makes a surprisingly large number of small cleanups to `main.rkt`. The most important ones move `--profile` (which is a no-op) and `--threads` (which every command except `shell` uses) into the global flags section. This means that only the `web` tool has special flags, which makes documentation a bit easier, too. Besides that there's some improvement to error handling and some general reduction in code.
Some additional improvements I'd like to do but might not do in this PR:
> Minor cleanups to `main.rkt`

- infra/make-index.rkt
- src/api/datafile.rkt
- src/config.rkt
- src/reports/timeline.rkt
It turns out that Herbie, on startup, always ran the `hostname` command, which it then inserted into reports but otherwise never used. I think this is low-value, and very hypothetically a privacy issue, and it slows down boot, basically no reason to deal with this.
> Remove the `hostname` global in Herbie

- src/core/reduce.rkt
- src/core/taylor.rkt
It's always been confusing that there are two things called `simplify`, now there aren't.
> Rename `simplify` to `reduce` in `reduce.rkt`

- src/core/derivations.rkt
- src/core/egg-herbie.rkt
This PR moves `get-canon-rule-name` to happen entirely inside `egg-parsed->expr`, which has two advantages:
- This ugly part of the egg-herbie library is hidden from callers
- The derivations package skips making a whole unnecessary copy of the proof
> Cleanup derivations

- src/api/shell.rkt
This PR removes unused default arguments from `unparse-result`, which then is a bit simpler.
> Simplify `unparse-result`

- src/api/sandbox.rkt
- src/core/alt-table.rkt
- src/core/mainloop.rkt
- src/core/points.rkt
- src/core/regimes.rkt
Right now `batch-errors` outputs a list (per point) of lists (per alt) of errors. This is dumb and every single caller actually applies `flip-lists` to transpose the lists. So this PR rewrites `batch-errors` to generate the lists in the transposed orientation. It's a little uglier, but it's less "paperwork" and it might be faster / less allocation too.
Longer term I think the goal should be to make it a list (per alt) of vectors (per point), which would mean even less allocation.
> Flip `batch-errors` output

- src/core/localize.rkt
- src/core/mainloop.rkt
- src/core/patch.rkt
- src/core/preprocess.rkt
- src/core/simplify.rkt
This is a small cleanup PR. Frankly we need to redo the `egg-herbie.rkt`/`simplify.rkt` API entirely but for now this is just mopping the decks on the proverbial Titanic.
> Move some common arguments to `simplify-batch`

- src/core/derivations.rkt
- src/core/egg-herbie.rkt
- src/core/reduce.rkt
- src/core/taylor.rkt
This PR was laying around in the branches folder and I'm rescuing it. It seems to do two things:
- Move `get-canon-rule-name` into `egg-herbie.rkt`, which I though happened in #1106 but who knows
- Rename `simplify` to `reduce` when it refers to `reduce.rkt`
> Clean up `datafile.rkt`

- egg-herbie/src/lib.rs
- egg-herbie/src/math.rs
- Prune once before extraction instead of every eqsat iteration
- Restrict exponent in `pow` constant folding
Runtime performance is improved by 6-8%, from ~70 minutes for a full benchmark run on `main` to ~65 minutes with this PR. Accuracy changes are a tossup (some worse, some better).
In this context, "pruning" means removing e-nodes with children if its e-class contains at least one leaf e-node.
> Prune once before extraction instead of every eqsat iteration

- src/core/egg-herbie.rkt
This PR runs the egraph eagerly in the `egg-runner` struct instead of rebuilding it from scratch. This might have some advantages:
- It makes the `derivations` phase faster since it can use the stored egraph instead of rebuilding it
- It also might make the API simpler since you now just manipulate an egraph
I think the reason we didn't do this originally is that originally we didn't have a good memory management story for the FFI, but as we've learned more about it it's become doable to just store the e-graph in memory and allow it to be garbage collected.
This PR is still experimental, and if it gives good results I expect to do significant simplifications to the egg-herbie code.
> Store the e-graph instead of recomputing it

- src/main.rkt
This was accidentally broken during a refactor.
> Fix handling of `--enable` and `--disable` with invalid flags

- src/core/batch.rkt
- src/core/derivations.rkt
- src/core/egg-herbie.rkt
- src/core/patch.rkt
- src/core/programs.rkt
- src/reports/history.rkt
- src/syntax/syntax.rkt
This PR breaks out one component of #1124 to test it better and also merge it early. Basically, before this PR, Taylor converted an impl like `(sin.f64 x)` to a spec like `(- x (/ (pow x 3) 6))`. This was just weird (why do we go from impl to spec) and had a bunch of downsides and needed special handling in various places. I fix it by instead adding a term `(hole prec spec)`, which represents an _unknown_ impl of `spec` at the given precision. Inside egg, we totally elide the `spec` term (this is unlike #1124) so when we extract we get a term of the right term.
This `hole` term also makes everything type-correct which allows us to make Taylor go from impl to impl, with the result impl being something like `(approx original-spec (impl original-precision taylored-spec))`.
> Add `(hole repr spec)` terms to simplify Taylor expansion

- src/api/demo.rkt
- src/api/server.rkt
This PR just simplifies stuff without changing functionality.
> Refactor the JSON conversion and other helper functions in the server

- src/core/derivations.rkt
- src/core/mainloop.rkt
Once upon a time, the derivations phase had to regenerate the egraph from scratch before computing derivations. Because of that, we wanted to recompute the egraph the minimal number of times, so the derivations phase first found all derivations needed, partitioned them by egraph, and then ran each egraph once (computing all proofs). This was implemented in #736. Recently, #1119 allows us to reuse the original egraph instead of regenerating it, so this batching no longer makes sense or does anything, so this PR gets us back to the easy one-phase code.
> Removing multiple phases for the derivations phase

- src/core/derivations.rkt
PR #1130 was good but made derivations slower; I just set up the cache wrong, using `eq?` instead of `equal?`, which meant we were computing the same proof many times. This PR changes the cache, making derivations fast again.
> Fix derivation speed broken by #1130

- src/core/batch.rkt
- src/core/derivations.rkt
- src/core/egg-herbie.rkt
- src/core/localize.rkt
- src/core/mainloop.rkt
- src/core/patch.rkt
- src/core/preprocess.rkt
- src/core/simplify.rkt
In this PR `make-egg-runner` becomes `make-egraph` and `run-egg` becomes four functions, `egraph-equal?`, `egraph-prove`, `egraph-best`, and `egraph-variations`. This allows me to simplify `preprocessing` somewhat, analogous to the recent simplification of `derivations`.
I also leverage that fact that `egg->herbie-dict` and `herbie->egg-dict` are _only_ used to rename variables, which means we don't need the dictionaries at all, just a normal Herbie context. One less thing to think about.
> Refactor the `egg-herbie` interface a bit

- src/api/demo.rkt
This very small change adds "e.g." to the front of the spec input placeholder to solve the issue noted by Ganesh:
This change matches the behavior of the Odyssey demo. The placeholder lightness there seems to match the current Herbie demo and this doesn't seem to be an issue there.
> Add "e.g." to placeholder text

- src/core/egg-herbie.rkt
- src/core/patch.rkt
- src/core/programs.rkt
This PR implements the idea suggested by @pavpanchekha of removing `simplify` step for taylor expansions and, instead, pass them into `run-rr` function.
Or more general, this PR eliminates creation of one Egraph for simplifying taylor expansions.
Instead, taylor expansions are inputted to the same egraph as `rewrite` uses.
The result is: about the same accuracy has been achieved but with a large speedup.
Maybe it is worth trying increasing `*node-limit*` after this update.
> Creating one egraph in `generate-candidates`

- src/config.rkt
- src/core/rival.rkt
- src/core/sampling.rkt
This PR adds a `dump:rival` Herbie flag (analogous to the existing `dump:rival` flag) that dumps every Rival machine to its own file, in Rival format, with every invocation. This might contribute to efforts to make Rival a standalone program.
I've taken some care to ensure that it's *exactly* the same inputs, which is a little annoying to read since it means we have to convert all inputs to rationals. @AYadrov possibly this can replace the existing giant JSON file we use in the Rival nightly.
> Dump Rival commands from Herbie

- src/syntax/read.rkt
- src/syntax/sugar.rkt
This PR fixes how we parse `:herbie-target` fields to allow them to have more than one property and to have those properties in any order.
> Fix bugs in parsing of :alt expressions

- infra/test-api.mjs
- src/api/demo.rkt
- src/api/run.rkt
- src/api/server.rkt
Right now, the single-threaded server runs jobs when `start-job` is called. This PR changes it to instead run jobs when `wait-for-job` is called. The reason to change things is simple; `run.rkt` has code that at a high level does:
```racket
(for ([job ...])
(start-job job))
(for ([job ...])
(wait-for-job job)
(print-status job))
```
If we run things in `start-job` then we get all the status prints at the very end, once all jobs are done (useless). If we run then in `wait-for-job` then we get prints one at a time, like we're suppose to.
The PR also has some random minor improvements to the server code.
> Change execution order for single-threaded server

- src/platforms/bool.rkt
- src/platforms/runtime/utils.rkt
- src/syntax/platform.rkt
- src/syntax/sugar.rkt
These got broken by the transition to the new platforms definition, but now they're fixed.
> Fix TeXification of named constants like PI

- infra/ci.rkt
- infra/test-api.mjs
- src/api/demo.rkt
- src/api/sandbox.rkt
- src/api/server.rkt
- src/core/bsearch.rkt
- src/core/derivations.rkt
- src/core/mainloop.rkt
- src/core/sampling.rkt
- src/core/test-rules.rkt
- src/reports/common.rkt
- src/reports/make-graph.rkt
This PR is a kind of grab-bag of cleanups, including:
- [-] Make `get-alternatives` and `get-improve` more similar, gearing up for eventual merge
The long-term vision here is to make `get-alternatives` and `get-improve` use the same exact code path and the same exact output formats, thereby ultimately fixing #1058.
> Cleanup various parts of the sandbox/server API

- .github/workflows/unit-test.yml
- src/api/demo.rkt
- src/api/sandbox.rkt
- src/api/server.rkt
- src/api/shell.rkt
- src/reports/make-graph.rkt
- src/reports/pages.rkt
- src/reports/plot.rkt
- src/reports/traceback.rkt
- src/syntax/read.rkt
- src/syntax/syntax-check.rkt
- www/doc/2.2/input.html
The core idea behind this PR is that both of these APIs return JSON blobs, and those JSON blobs have distinct sets of keys. So we can just merge both endpoints and return *both* sets of keys, and everyone will be happy.
Doing this is quite involved, and required:
> Merge `/api/improve` and `/api/alternatives`, remove custom Herbie properties

- src/core/mainloop.rkt
- src/core/test-rules.rkt
- src/platforms/binary32.rkt
- src/platforms/binary64.rkt
- src/platforms/bool.rkt
- src/syntax/platform.rkt
- src/syntax/syntax.rkt
This PR removes all components in Herbie related to exactness, including the application of identities, after it was determined that removing them entirely added a speedup to Herbie without any changes results.
> Remove exactness 

- src/core/alt-table.rkt
- src/reports/traceback.rkt
This PR speeds up the "pruning" phase, a.k.a. `atab-add-altns`. Currently, every time we add an alt to the alt-table, we deduplicate the alts by expression. This is wasteful. There are various possible fixes, but this PR does the simplest thing: it deduplicates once instead of per-alt. I did a quick test and the "ratio of anisotropy" benchmark is about 5x faster with this PR on my local machine; I expect an overall savings across the whole benchmark suite of about 2–3 minutes, or about 5% of runtime in the best case.
> Faster pruning by deduplicating alts less often

- src/api/server.rkt
Problem
Previously, there was an issue on nightly where functions could created and used across multiple fpcores. This issue came from thread isolation which caused functions defined in one thread to be inaccessible in others.
Solution
This PR adds the function state to be global variable that is shared across all threads.
> Update server.rkt to include *functions* as a global state.

- .github/workflows/unit-test.yml
- Makefile
- src/core/egglog-herbie.rkt
This PR introduces a major change in how costs are integrated into the Egglog program.
Since Egglog does not support floating-point costs and throws the error `parse error: expected cost to be a nonnegative integer literal`, we work around this by traversing all nodes to accumulate their raw costs, computing the minimum cost, and then normalizing the values. The minimum is scaled to 100, and the rest are adjusted proportionally and rounded to the nearest integer.
Additionally, this PR adds `egglog-herbie` to the regular `make install`
> Adding support for Floating Point Costs in Egglog

- src/reports/common.rkt
#1174 broke the HTML rendering of warnings by changing the length of the warning struct. This PR fixes it.
> Fix HTML rendering of warnings

- infra/ci.rkt
- src/api/datafile.rkt
- src/api/sandbox.rkt
- src/api/server.rkt
- src/reports/history.rkt
- src/reports/plot.rkt
This PR removes the training error from HTML reports and the API.
Way way back in the day, before the timeline, we added training error to the derivations in the Herbie reports, in an attempt to aid debugging. I think it was never particularly useful, was broken at various points in time, and also at this point clearly inferior to the timeline, which is where we put all debugging-related information. More generally, I think we should maybe treat training error as an internal detail of Herbie—it's visible in other "internal" places like timeline but shouldn't be exposed to users and clients through reports or the API.
So let's just remove it. This PR removes training error from the `table-row` struct, the `alt-analysis` struct, the corresponding pcontext from the `improve-result` struct, …
> Remove the training pcontext from Herbie results

- src/core/alt-table.rkt
- src/core/batch.rkt
- src/core/compiler.rkt
- src/core/points.rkt
This PR makes a few small optimizations to `atab-eval-altns`:
- In `progs->batch`, use an eq-cache to speed up batch-construction from expressions that came from a batch. Note that this messes with the statistics a bit, but maybe in a good way (?)
- In `compile-progs` and `batch-errors`, allow passing in a pre-constructed batch
- In `atab-eval-altns` compute the cost directly from the batch to skip duplicates
The end result is that `fidget/colonnade.fpcore` goes from 202s to 107s on my macOS machine, which seems worth it.
> Faster `atab-eval-altns` using more batches

- src/api/server.rkt
- src/syntax/platform.rkt
- src/utils/common.rkt
This PR speeds up `get-fpcore-impl` using a cache and `make-alternative-result` by reusing a `render-history` result instead of duplicating it. As a result, `make-alternative-result` for the colonnade benchmark goes from ~85s to ~40s, which still isn't great but is an improvement. The hope is that this makes the nightly reports run faster, too.
> Faster `get-fpcore-impl` and `make-alternative-result`

- src/core/bsearch.rkt
- src/reports/history.rkt
I'm trying to make `render-history` faster, since it turns out to take up a _huge_ amount of runtime. Now, _most_ of that function is spent in `errors`, which should be easy to speed up by just batching. But first I wanted to speed up `split-pcontext`, which turns out to be pretty dumb by default. This PR doesn't optimize it maximally but it still makes it about 2x faster, saving an estimated, I don't know, half a minute (?) on nightlies.
> Speed up regimes pcontext splitting

- src/api/server.rkt
- src/reports/history.rkt
This PR adds a pretty ugly "errcache" to the JSONify code so that all alt evaluations in `render-history` and `render-json` use a single batch. This speeds up JSONify by ~2x, cutting nontrivial time off of each nightly run. It could be _even_ faster because it's not actually a single batch, it's a single batch _per pcontext_, and pcontexts differ because we split them during regimes. It would be better to, instead of filtering the pcontexts, just mask them out—then everything really could use one big batch—but for now let's pocket this speedup while we can.
> Faster nightlies using `batch-errors`

- src/core/mainloop.rkt
This PR makes a subtle change to rewrite/series. Suppose we have an expression E where a subexpression S appears twice: `E[S, S]`. Rewrite/series gives us lots of variations of S: S1, S2, ... Then we "reconstruct" those into variations of E. At the moment we create `E[S1, S]`, `E[S2, S]`, ..., `E[Sn, S]` and also `E[S, S1]`, `E[S, S2]`, ... We never create, say, `E[S1, S1]` (let alone `E[S1, S2]`); if that is useful we'd need to do two iterations.
This PR changes things so we only make `E[S1, S1]`, `E[S2, S2]`, and so on. There are two reasons to do this:
- It might be slightly faster, since we generate fewer candidates. I guess that pans out. In principle it could be slightly better but in practice it doesn't seem to be; in a nightly run it's worse on `expfmod`, a benchmark I don't care …
> Reconstruct at all locations, not just one

- src/core/preprocess.rkt
- src/core/prove-rules.rkt
- src/core/rules.rkt
This PR adds `prove-rules.rkt`, a counterpart to `test-rules.rkt`, which proves that sound rules are actually sound. Recall our definition of soundness: a rewrite `a -> b` is sound if `a = b` when both `a` and `b` are defined, and furthermore that `b` is defined whenever `a` is. This slightly-strange asymmetric definition of soundness is just loose enough to allow valuable rewrites like `a / a -> 1` to be considered sound, while still guaranteeing no unsoundness in the egraph.
This PR accomplishes a few things. First, it reclassifies 12 rules from sound to unsound, because they were actually unsound. Second, it adds a little theorem prover to prove the remainder sound. This theorem prover works like so:
- The `validity-conditions` function traverses an expression and returns a list of …
> Enforce rule soundness using a little proof assistant

- .fmt.rkt
- src/core/rules.rkt
- src/core/test-rules.rkt
This PR refactors the syntax for defining rules. Basically we go from this:
```
(define-ruleset* squares-transform-sound
(arithmetic sound)
#:type ([x real] [y real])
[sqrt-pow2 (pow (sqrt x) y) (pow x (/ y 2))])
(define-ruleset* squares-transform
(arithmetic)
#:type ([x real] [y real])
[sqrt-prod (sqrt (* x y)) (* (sqrt x) (sqrt y))]) ; unsound @ x = y = -1
```
to this:
```
(define-rules arithmetic
[sqrt-pow2 (pow (sqrt x) y) (pow x (/ y 2))])
(define-rules arithmetic
[sqrt-prod (sqrt (* x y)) (* (sqrt x) (sqrt y)) #:unsound]) ; unsound @ x = y = -1
```
To summarize, the changes are:
- `define-ruleset*` to `define-rules`, and drop the ruleset name (which wasn't used). Instead put the group name there.
- Instead of using a `sound` tag, sound is the default and you have to add a …
> Simplify rule syntax

- src/api/server.rkt
- src/core/bsearch.rkt
- src/reports/history.rkt
The JSONify phase is kind of a confusing, poorly-factored phase, but the main thing this phase does is compute derivations, and most of _that_ time is spent evaluating intermediate expressions. At the moment (since #1205) this involves one batch evaluation per pcontext. There are multiple pcontexts because regimes splits the pcontext into pieces.
This PR refactors things so that there's only ever one pcontext; instead of splitting pcontexts, regimes involves creating masks. This means that we only need to do one batch evaluation, which ends up being faster, possibly quite a bit faster if there are many different alts each of which have different regime splits. There's another possible effect—with #1205 I noticed that GC pressure on the rest of Herbie increased by a noticable amount. I'm …
> Further optimizations to JSONify

- src/core/patch.rkt
Recently I noticed that we deduplicate approximations by deduplicating `approx` nodes.
But the thing is, that `approx` node contains `spec` and `impl`.
So, for example if `spec`s do not match, but `impl`s are the same - we end up not deduplicating these approximations.
But in fact, we mostly do not care which exactly `spec` has been approximated - what we care is no equal `impl`s should be present.
Maybe that will help further and `egg` will receive less `approx` nodes - as a result more rewrites will be produced.
How much of additional deduplication happens:
I tried `quadp` benchmark and here how much we can reduce
1st expansion: 108 approximations -> 103 approximations
2nd expansion 213 approximations -> 109 approximations
3rd expansion 269 approximations -> 165 approximations
4th …
> Additional deduplcation at taylor

- src/core/prove-rules.rkt
- src/core/reduce.rkt
- src/core/taylor.rkt
This PR removes the `reduce.rkt` simplifier's handling of `sqrt`, because such handling was often unsound. This fixes #1220 and is part of a broader project to fix unsoundness throughout Herbie, because we've started to see it as a bottleneck on further improvement.
> Don't reduce sqrt terms

- src/core/prove-rules.rkt
- src/core/rules.rkt
- src/core/test-rules.rkt
We have seven "conditional" rules, where the lhs and rhs aren't equal over the whole domain but only over a subset of the domain. Conceptually this is I guess fine, just another kind of unsoundness, but the actual rules aren't used much so why not remove them? Well, it turned out one of the rules (`pow-pow`) was useful for reasoning about cube roots, so this PR adds a sound replacement for just that one case, and then removes all of the conditional rules.
> Remove "conditional" rules

- src/core/batch.rkt
- src/core/compiler.rkt
There's no need for batches to include the variables explicitly; the compiler specifically needs it but it's not an inherent property of batches themselves.
> Remove vars from batches

- src/core/alt-table.rkt
- src/core/batch.rkt
- src/core/compiler.rkt
There's a timeline field called "Compiler" that tells you how much batches deduplicated the expression tree. There were two problems with it:
1. I introduced a cache in #1195 which means we were logging the wrong number anyway
2. The logging code actually makes `progs->batch` unable to use `mutable-batch-munge!` and in general imposes a kind of ugly API
This PR fixes this all by introducing the `batch-tree-size` API, which gives the size of a batch if it were a tree. Critically, it doesn't actually build a tree, it just does math. Then this API lets us unify `progs->batch` and `mutable-batch-munge!`; along the way, I add the cache from #1195 to `mutable-batch-munge!`, which I think might speed up a few benchmarks.
Long-term, I think it would be good to remove the `timeline-push` argument …
> Simplify batch compression logging

- src/core/patch.rkt
This is super minor and dumb and a mis-feature already but this PR makes colonnade way faster without any significant code change, just by caching a string.
> Speed up duplicative printing in taylor-alts

- src/core/patch.rkt
- src/core/rules.rkt
This PR is built on top of #1226.
It introduces updates to `generate-candidates`. Particularly speaking, currently, we _lower_ our approximations and rewrite them in the same e-graph that we use for general rewrites.
But that actually slightly wrong.
The reasons behind are:
Taylor expansions do not guarantee to produce any good results - it can, and in most of the cases does, but in general, taylor expansions can be just a nonsense.
When we rewrite a potential nonsense with meaningful expressions that we actually sure about - we just occupy our vital space in egg and hit the node limit faster.
And we likely do not need to do that - taylor expansions should go to a separate egg for lowering and do not interact with the general rewrites as they actually can produce something good and more …
> Taylor rewrite in separate paths

- src/api/demo.rkt
- src/api/run.rkt
- src/api/sandbox.rkt
- src/api/server.rkt
- src/api/shell.rkt
This PR reorganizes and renames server.rkt methods, and maybe cleans up some of the control flow a bit.
> Clean up server.rkt a bit

- src/api/run.rkt
This PR lets multithreaded reports by running benchmarks on the main thread while worker threads do benchmark runs. It should make nightlies slightly faster.
> Run reports on main thread while other benchmarks run

- src/core/alt-table.rkt
- src/core/mainloop.rkt
This PR fixes #1220. Basically, in a few rare cases we might construct an alt that is _invalid_ at a point and yet is still the cheapest alt at that point. So maybe you somehow create the alt `(sqrt.f64 #(literal -1 binary64))`. Then that is stuck in your alt table, because it's the cheapest (even though it's bad). And then that gets into later egraphs and messes them up.
So this PR just never puts invalid points in the egraph.
> Drop invalid points from pareto curves

- src/api/server.rkt
In "no-threads" mode (the default!) the normal Herbie server doesn't work. That's because the normal Herbie server was only actually _doing_ the work when you asked for the results; if you asked it the status it would always say "job in progress". But that lead to a kind of livelock, where the web server was constantly asking "are you done yet" and then Herbie was saying "nope, still in progress". The fix is easy: also do the job if someone asks for its status, which (annoyingly) there are several ways to do.
> Fix the server in "no-threads" mode

- src/core/mainloop.rkt
- src/core/preprocess.rkt
- src/reports/common.rkt
- src/utils/common.rkt
It's annoying to compile preprocessing instructions like `(sort a b c)`. This PR just removes many-way sorts entirely. It's not as much of a loss as you might think:
- There's only three benchmarks that use it in our benchmark set
- They're all `sqrt(x*x + y*y + z*z)`, and honestly sorting is detrimental there (though it's not sorting's fault)
- Without `(sort a b c)` we'll get `(sort a b) (sort a c) (sort b c)`, which still sorts all three variables, though it's O(n^2) not O(n log n), not that it ever matters
The benefit is a _massive_ simplification of the preprocessing mechanism because preprocessing is now entirely compiled away.
> Only support two-argument sort in preprocessing

- src/reports/common.rkt
- src/reports/make-graph.rkt
- src/reports/resources/report.html
I don't know what exactly jsDelivr is but Observable and D3 now recommend it, and I guess using one CDN is better than using two.
> Update all of the JS libraries we use to the latest `jsdelivr` version

- bench/demo.fpcore
I added a new benchmark to the demo.fpcore based on [user entry](https://herbie.uwplse.org/demo/fe5839acfca4da10082d4e20259dcd89b75b0617.1a83c9f5186db102b678a2d5f869f99992469071/graph.html). Herbie rewrote it to `p−fma(min(p,0)/min(p,0)-1,min(p,0),−1)`, but whenever `min(p,0)` is really small there would still be rounding errors, so I created a version with a if-else threshold to catch those values:
```
if (p >= 1e-6 && p <= 0) {
// Use Taylor approximation for small p near 0
result = p + 1 - p * p / (p - 1);
} else {
result = p - fma(p / (p - 1), p, -1);
}
```
Brett formatted it to be able to be input as a FPCore statement:
```
(FPCore (p)
:herbie-target
(if (and (>= p -1e-6) (<= p 0))
(- (+ p 1) (/ (* p p) (- p 1)))
(- p (fma (/ p (- p 1)) p -1)))
(- (+ p 1.0) (/ (pow (fmin p 0.0) 2.0) …
```
> updated demo.fpcore

- src/core/rival.rkt
- src/info.rkt
This PR updates codebase to match new Rival changes - mainly a separation of `rival-analyze` and `rival-analyze-with-hints`.
> Compatability with minor Rival's changes of `rival-analyze-with-hints`

- infra/softposit.rkt
- src/platforms/c-windows.rkt
- src/platforms/c.rkt
- src/platforms/herbie10.rkt
- src/platforms/herbie20.rkt
- src/platforms/math.rkt
- src/platforms/racket.rkt
- src/platforms/rival.rkt
This PR converts the remaining platforms to `#lang herbie/platform`. For a few of them, like `rival` or `racket`, I made changes to be more in keeping with the intended use case (for `racket`, I only kept functions natively offered by Racket). For `math` I didn't bother cleaning up the costs, even though they are pretty ugly.
> Convert all platforms to the new `#lang`

- www/doc.html
- www/doc/2.2/platforms.html
- www/doc/2.2/plugins.html
This replaces the old `plugins.html`, which described a bunch of obsolete APIs, with a brand new page that just covers representations and generators.
> Document representations and generators

- www/doc/2.1/tutorial.html
This PR makes several improvements to the Herbie tutorial. It brings up Herbie's randomized behavior earlier, specifically with the `sqrt(x + 1) - sqrt(x)` example, so new users understand that their output may differ from the tutorial. It also includes a brief explanation of how Herbie measures accuracy, adds links to terms like overflow and cancellation, and fixes various typos, inconsistencies, broken links, and unclear wording throughout.
> Update tutorial to address typos + clarity

- src/platform.rkt
- src/platforms/c-windows.rkt
- src/platforms/c.rkt
- src/platforms/herbie10.rkt
- src/platforms/herbie20.rkt
- src/platforms/math.rkt
- src/platforms/racket.rkt
- src/platforms/rival.rkt
- src/syntax/load-platform.rkt
@LooneyLiberator discovered that passing an absolute path to Herbie, as in `--platform /foo/bar/baz`, doesn't work. This PR fixes it. Don't ask why.
> Fix loading of platforms from absolute paths

- www/doc/2.2/using-cli.html
- www/doc/2.2/using-web.html
This is a small thing but it makes sure that if someone installs Herbie and runs it with the seeds shown they'll get exactly identical answers. I think it's nice to do that.
> Update all Herbie doc outputs to match current Herbie

- src/platforms/julia.rkt
This PR implements a platform for Julia. It supports operations over both `binary32` and `binary64`. The operations implemented are the same as in the paper's original Julia platform. Costs were calculated separately (and rounded) in a hot loop with randomized function parameters, and while they differed from the original Julia platform, the general trend was just about the same. Costs range from `1.0` (technically `0.10` if you count the boolean move cost) to `14.0`, and look reasonable.
> Julia platform implementation

- src/info.rkt
We do use Typed Racket inside `regimes.rkt`. I'm not sure why, but `raco` seems to want us to declare the dependency, so fine.
> Add dependency on `typed-racket-lib`

- src/core/rival.rkt
The `dump:rival` flag outputs every Rival evaluation to a Rival-formatted file. However, it crashes on inf and NaN inputs; this PR fixes that. Additionally, the PR makes `dump:rival` much faster. The code used to output exact rationals for each argument; this makes the arguments really long. It turns out that you can write `#i3.2` in Racket (and thus Rival) to mean "the floating-point number closest to 3.2". Switching to that makes the output much shorter (and easier to read) which cuts runtime a lot. Moreover, this PR stops using `pretty-print`, which is slow, for `eval` lines; it keeps it for `define` lines, which are the ones you want pretty-printed, anyway.
In sum, `dump:rival` is much faster and probably still correct. It still adds something like a 2–3x overhead to Rival, but that …
> Make `dump:rival` faster and more correct

- src/syntax/generators.rkt
- www/doc/2.3/platforms.html
Rival "accelerators" are just platform operators defined with `from-rival`. These are _super duper slow_. So slow! We've got examples of them taking a benchmark from 1s → 40s. Some investigation of this for the `grow-libm` branch by @JonasRegehr revealed that we are frequently evaluating an accelerator with the _same exact input_ multiple times. This PR thus adds a cache in every `from-rival`-generated operator. One tricky bit is making sure we clear these between benchmarks.
For example, across `tutorial.rkt`, we seem to do 2.6M evaluations of a `sum5` accelerator in the `slow-rival` branch. After deduplicating I think there are 416k, which is a 6x reduction, and unsurprisingly the total runtime goes from 77s to 18s (about a 4x reduction).
I'm not 100% sure we should actually merge …
> Add a cache in front of every Rival accelerator
