.gitignore
herbie/common.rkt
herbie/compile/tex.rkt
herbie/config.rkt
herbie/programs.rkt
herbie/reports/datafile.rkt
herbie/reports/demo.rkt
herbie/reports/graph.css
herbie/reports/graph.js
herbie/reports/make-graph.rkt
herbie/reports/make-index.rkt
herbie/reports/make-report.rkt
herbie/reports/thread-pool.rkt
herbie/simplify/backup-simplify.rkt
www/404.html
www/demo.js
www/index.html
www/installing.html
www/main.css

New report details, also the web demo.

New report details and web demo

---

herbie/syntax.rkt

The previous "fix" (included in #76) was wrong.

*Actually* fix bug with hypot

---

.travis.yml
herbie/common.rkt
herbie/info.rkt

- Adds a build dependency on rackunit
- Adds tests to common.rkt in test submodules
- Updates info.rkt to define what files should be skipped when testing
- Updates travis.yml to test the herbie package after installing it

Add rackunit testing infrastructure and test common.rkt

---

.travis.yml
Dockerfile

Also build docker image as part of CI

Change docker image entrypoint to raco herbie command

---

.travis.yml
Dockerfile
herbie/herbie.rkt

This builds on #122 with two more commits - the first fixes how the docker image is built, the second makes building it more reliable by caching the image between travis runs.

Reliable dockerfile

---

www/doc/1.0/installing-herbgrind.html
www/doc/1.0/release-notes.html
www/doc/1.0/using-herbgrind.html
www/doc/1.0/using-herbie.html
www/index.html

HerbGrind -> Herbgrind

---

src/glue.rkt
src/mainloop.rkt

Initial program is now added alongside the initial simplified program when we begin iterations.
Tested with the Hamming tests.

 Untrusted initial simplify

---

src/config.rkt
src/core/regimes.rkt
www/doc/1.2/options.html

Added alts in critical subexpression calculation and added a flag to turn off non-variable subexpression branching.

Critical subexpressions from alts

---

src/web/demo.js
src/web/demo.rkt

Added support for all functions in the web demo, as well as documentation on the page for them.

Web demo functions

---

.travis.yml
src/points.rkt

This PR avoids having the exacts ramp up phase do two full passes over the points.
Some minor copy/paste was also removed from the Travis configuration.

Exacts ramp up

---

bench/challenge/input-sampling.fpcore
bench/challenge/mpfr-performance.fpcore
bench/challenge/overflow.fpcore
bench/challenge/precision-limits.fpcore
bench/challenge/timeout.fpcore
bench/regression/timeout.fpcore

This PR pulls out some of the tests that regularly fail due to known limitations of Herbie's approach.  Those tests have been gathered into a new category called "challenge" under the bench directory.

Regression test cleanup

---

src/formats/tex.rkt
src/syntax/syntax.rkt
src/web/demo.js
src/web/demo.rkt
src/web/main.css
www/doc/1.3/docker.html
www/doc/1.3/faq.html
www/doc/1.3/input.html
www/doc/1.3/installing.html
www/doc/1.3/options.html
www/doc/1.3/release-notes.html
www/doc/1.3/report.html
www/doc/1.3/toc.js
www/doc/1.3/tutorial.html
www/doc/1.3/using-cli.html
www/doc/1.3/using-web.html
www/main.css

This PR contains a variety of fixes to the web mode. The most important are new fields for preconditions and precisions, but I've also added a type checker to the web mode, tweaked the TeX output for many functions, and added support for conditional syntax.

Support preconditions and precision in the web mode

---

infra/travis.rkt

Switch travis to showing seconds with fewer punctuation marks

Prettier output from Travis

---

src/alternative.rkt
src/common.rkt
src/core/enode.rkt
src/core/regimes.rkt
src/interface.rkt
src/mainloop.rkt
src/programs.rkt
src/sandbox.rkt
www/index.html

This commit:
- Fixes a few bugs I ran into trying to run `herbie improve`
- Moves `*var-precs*` and `*output-prec*` to `interface.rkt`
- Moves `*start-prog*` and `*all-alts*` to `alternative.rkt`

Various bug fixes

---

src/core/matcher.rkt

This fixes a rare but huge slowdown in recursive rewrite, where individual expressions can take minutes to recursively rewrite. The issue is re-traversals of the same node, eventually leading to an exponential increase in the time it takes to find all rewrites. The re-traversals are, however, easy to fix with a simple cache.
For the `(* (exp ...) ...)` expression that causes recursive rewrite to go berserk, the timings without caching are:
cpu time: 143402 real time: 143835 gc time: 1709
Rewrite chains found: 113
With caching:
cpu time: 140 real time: 140 gc time: 32
Rewrite chains found: 113
So caching leads to a speedup of roughly 1000 times for this bad case. Since it replaces an exponential problem with a linear one, I expect even bigger improvements to be findable, though in the …

Add a cache to recursive rewrite

---

README.md
src/web/demo.rkt
src/web/run.rkt
www/doc/1.4/faq.html
www/doc/1.4/input.html

Big shout-out to @erich666 for finding a bunch of confusing or vague text in the documentation (#294). They should be fixed in this PR.

Documentation tweaks

---

src/core/localize.rkt
src/core/reduce.rkt
src/core/regimes.rkt
src/float.rkt
src/mainloop.rkt
src/points.rkt
src/programs.rkt
src/web/history.rkt

This PR fixes support for posit arithmetic, and hopefully other plugins/representations as well. Because we hadn't been running posit tests for a while, lots of minor issues had crept in. Besides fixing all of those, this PR also tries to be more careful about types and reprs, and correctly handle mixed-precision computation.

Fix posit support

---

infra/travis.rkt
src/web/tex.rkt

This PR fixes some remaining issues (TeXification and the `travis` script) that were preventing plugins like `softposit-herbie` from working.

More mixed-representation fixes

---

src/interface.rkt
src/web/common.rkt
src/web/plot.rkt

This PR adds FPCore to the language dropdown and fixes an issue where the plotter would crash for single precision FPCores.

Plot fixes

---

www/main.css

This PR fixes #325  by switching the red / green colors to bright-red / dark-blue.

Fix showcase colors for color-blind viewers

---

www/index.html

Hey 👋 
I've seen the adjustment done with bea29893de62eb579c35db32882c1542e78ab85f (very cool 👍 ), and noticed that the text in `index.html` could now be adjusted to match the actual color of choice.

Adjust text to adjusted colors

---

infra/convert-demo-json.sh
infra/convert-demo.rkt
infra/sort-fpcore.rkt

The script accepts a folder containing all the json files and outputs fpcore files which can be read by herbie.
It also performs the same sort on the fpcore expressions that herbie does.

Add script which converts demo json files

---

src/web/demo.js
src/web/demo.rkt
src/web/main.css

This PR makes it possible to give direct FPCore input to Herbie on the web interface. If the web interface is opened with the `?fpcore=...` parameter, it pre-fills the FPCore input. This should improve the experience of users coming from the FPBench website.

FPCore input on the web

---

src/syntax/rules.rkt

The Ruler team discovered a bunch of simple `fabs` rules that Herbie didn't have already, and @chandrakananandi graciously extracted the ones we should add. This PR adds them.

Added new `fabs` rules

---

src/mainloop.rkt
src/syntax/sugar.rkt
src/web/make-graph.rkt
src/web/plot.rkt
src/web/report.css

This PR fixes a resugaring bug: `neg` instead of `-`, and it also includes some tweaks to reports.

Fix resugaring bug

---

bench/pbrt.fpcore

This PR adds 25 benchmarks from the [pbrt](https://github.com/mmp/pbrt-v3) renderer described in "Physically Based Rendering" by Pharr, Jakob, and Humphreys.

PBRT Benchmarks

---

infra/publish.sh

For some reason the original command didn't work...

Make sure we compress all of the various log and JSON files

---

README.md
infra/make-index.rkt
infra/publish.sh
src/info.rkt
src/web/demo.rkt
src/web/make-report.rkt
www/doc/1.5/installing.html
www/doc/1.5/options.html
www/doc/1.5/tutorial.html

I bumped FPBench's claimed version to 2.0.1 to indicate the new CSE stuff.

Bump FPBench version

---

src/core/simplify.rkt

Apparently there are multiple package scopes!

Check both package scopes for egg-herbie

---

Makefile
infra/nightly.sh
infra/publish.sh

I think / hope this will fix the bugs in the nightly

Fix argument passing in scripts so new-make-index works

---

.github/workflows/release.yml
Dockerfile

This PR simplifies the Dockerfile for a faster build and rolls back the Ubuntu version for building release artifacts due to glibc compability issues.

Fix docker

---

infra/nightly.rkt
infra/nightly.sh
src/timeline.rkt

This PR fixes #418 in the nightlies and makes sure a joint nightly report is actually created.

Fix nightlies & merge reports

---

bench/numerics/conte.fpcore

This PR adds 7 benchmarks from a numerical analysis textbook. Herbie seems to do well on them.

New benchmarks from "Elementary Numerical Analysis" (Conte and de Boor, 1980)

---

.github/workflows/distribute.yml
.github/workflows/egg-herbie.yml
.github/workflows/plugins.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.github/workflows/tools.yml
.github/workflows/unit-test.yml
Dockerfile
README.md
egg-herbie/src/rules.rs
src/core/reduce.rkt
src/float.rkt
src/points.rkt
src/reprs/binary32.rkt
src/sampling.rkt
src/syntax/sugar.rkt
src/syntax/type-check.rkt
www/doc/1.6/installing.html

This  PR removes support for Racket 7 and the complex number plugin.

Remove Racket 7 & complex plugin support

---

infra/merge.rkt
infra/run.sh
src/datafile.rkt
src/web/common.rkt
src/web/make-report.rkt
src/web/resources/report.css
src/web/resources/report.js

This PR improves merged reports by providing a collapsible table of subreports with links. No need to manually edit URLs!

Access subreports

---

infra/make-index.rkt

Make the index treat "main" as the main branch

---

src/alternative.rkt
src/core/alt-table.rkt
src/core/regimes.rkt
src/core/taylor.rkt
src/cost.rkt
src/mainloop.rkt
src/patch.rkt
src/programs.rkt
src/sampling.rkt
src/sandbox.rkt
src/web/run.rkt

This PR was cherry-picked off of the bsearch sampling PR.

Minor cleanup

---

src/web/thread-pool.rkt

Right now, if Herbie is run with `--threads` and one of those threads dies, Herbie enters a deadlock state. (This is rare, and is pretty much only caused by bugs in report generation.) This is very annoying, and this PR fixes this bug. With this PR, when a thread dies, the main Herbie process will fail immediately, which should be easy to detect and fix.
The issue is pretty dumb. Herbie can distribute work to a thread, and then wait for it to finish that work. But if the thread crashes, it never finishes the work, and the main thread waits forever. The fix is to also wait for special "place-dead" events and react to them by terminating the process.

Don't deadlock if a thread dies

---

src/core/regimes.rkt
src/web/timeline.rkt

This pretty minimal PR just adds a timeline entry for information about different regimes branches.

More details in timeline for regimes

---

src/core/alt-table.rkt

There will be an accompanying blog post…

Optimize alt minimize

---

src/pareto.rkt
src/web/resources/report.js

Compresses the sliding window and scatterplot (after
window averaging).
Also darkens scatterplot slightly and thickens the sliding window line
to account for reduced volume.

Make plotting fast.

---

.github/workflows/tests.yml
infra/diff.rkt
src/core/alt-table.rkt
src/programs.rkt

Fixes another non-determinism problem and adds a CI job to potentially detect future non-determinism.

Fix nondeterminism

---

bench/regression.fpcore
src/sandbox.rkt

This PR adds the expressions (and suggested improved versions) from #323, #329, , #333, #366, and #500 to our regression suite. This way we will incrementally work toward improving our performance on them.

Add benchmarks based on user bugs

---

www/doc.html

Yes, six! It turns out I've been blogging more than I feared.

Added six new blog posts about Herbie that I wrote

---

.github/workflows/distribute.yml
.github/workflows/egg-herbie.yml
.github/workflows/plugins.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.github/workflows/tools.yml
.github/workflows/unit-test.yml

Let's see if this PR quiets some of the deprecation warnings we get in actions.

Updated GH action versions

---

src/mainloop.rkt
src/sandbox.rkt
src/soundiness.rkt
src/web/demo.rkt
src/web/history.rkt

This is Brett's branch that shows the history for *every* alt. Screenshots look good enough to merge, so I am going to just merge.

Add history to alts (for the study server)

---

src/common.rkt
src/web/history.rkt
src/web/make-graph.rkt
src/web/make-report.rkt
src/web/timeline.rkt

This PR changes the representation of error to a representation of accuracy. This is accompanied by changing the static labels on the timeline as renaming the function call.

Convert percentage accuracy

---

infra/testApi.mjs

Fixed two broken test that were missing an Array wrapper.

testApi.mjs

---

src/alternative.rkt
src/core/matcher.rkt
src/mainloop.rkt
src/patch.rkt
src/web/history.rkt

This PR removes uses of the change struct by changing the output of the rewriter.

Remove change

---

src/alternative.rkt
src/core/matcher.rkt
src/mainloop.rkt
src/patch.rkt
src/soundiness.rkt
src/web/history.rkt

Initial PR split from rr-proofs branch. 
Proofs using egg-rr now have a step-by-step derivation proof when displaying the report

Initial rr proofs

---

src/alternative.rkt
src/core/egg-herbie.rkt
src/core/matcher.rkt
src/core/simplify.rkt
src/mainloop.rkt
src/patch.rkt
src/soundiness.rkt
src/symmetry.rkt
src/web/history.rkt

PR after initial-egg-rr.
Proofs using either simplify or rr now only call run-egg, merging and abstracting the algorithm.

Proofs in egg-rr

---

www/papers.html

Unrelatedly, also add a link to the Rival library.

Add Odyssey paper to the papers list

---

src/datafile.rkt
src/web/make-report.rkt

Make the cost units in reports relative to the original program.

Relative pareto curve

---

src/datafile.rkt

There is a bug where missing `table-row-cost-accuracies` would crash `merged-cost-accuracy`. This fixes those issues and a few other edge cases.

Fix bug with relative Pareto curves

---

README.md
www/doc/1.7/plugins.html
www/doc/1.7/release-notes.html
www/index.html

This fixes #585 and fixes #586.

Remove or fix old broken links

---

infra/merge.rkt
src/web/make-report.rkt

Fixed broken Herbie logo on the Nightly page.
Added missing test status for "error" and "timeout" to "Result" help tooltip.

Added missing text & fixed broken Herbie logo on reports page

---

src/core/egg-herbie.rkt
src/web/thread-pool.rkt

- Print percentage accuracy on the command line
- Don't warn on unsound egraph

Minor fix-ups for 2.0

---

www/doc/1.7/release-notes.html
www/main.css

This basically finishes the release notes.

Add screenshots to release notes

---

www/doc/1.7/api-endpoints.html
www/doc/1.7/using-cli.html

Updates using-cli by setting Herbie's version number to 2.0 in sample output. Also updates sample output to be more consistent with Herbie's output by removing decimal points and adding warnings.
Updates api-endpoints by correcting incorrect API argument names and incorrect endpoint names. Also deletes the documentation for the exacts and calculate endpoints, which were not correctly describing the endpoints as implemented. See [this slack thread](https://davidtamaspar-r2y7532.slack.com/archives/C0G44MH4P/p1687555752091759).

Update using-cli and api-endpoints docs.

---

www/doc/1.7/faq.html
www/doc/1.7/input.html
www/doc/1.7/options.html

Documentation improvements for the input, options, and error pages.

Input options error documentation

---

src/web/resources/report.js

Just removes dead code from `report.js`

report.js remove dead code.

---

src/web/resources/report.css
src/web/resources/report.js

This PR cleans up a few missed requested changes for PR611 for the result filters feature.

Patches for filters

---

www/papers.html

Updates `papers.html` with the venue, adds the edited abstract, and fixes the link to the Odyssey repo.

Note the Odyssey paper (will be) published in UIST'23

---

src/web/resources/report-page.js
src/web/resources/report.css

This PR brings back a highly requested feature. Being able to view a few basic subreport metrics and navigate to there individual reports.

Feat: Reports page Subreports

---

src/web/resources/report-page.js

Adds finer-grained controls for how two results.json files are compared. 
- S-expression output
- time
- status
- accuracy

Adds controls for diffing against another branch.

---

Makefile

This tiny PR adds `-y` to the Racket command for the server.

Auto-compile server files

---

egg-herbie/src/lib.rs

Let's see how the nightlies do performance wise - it might be worth keeping the thread around between calls.

Proof code band-aid

---

src/web/resources/report-page.js

Fixes annoying bug of the drop down menu glitching out.
Adds pre process filter.
Forgot to make a new branch for pre process filter.

Fixes benchmark dropdown menu & adds pre process filter

---

bench/hamming/overflow-underflow.fpcore
bench/hamming/rearrangement.fpcore
bench/hamming/series.fpcore

Made sure all exponential bounds are 10^710. expq3 precondition is now ambiguous as to whether a or b is smaller as discussed in Wednesday's meeting. Removed 1e100 bounds on 3frac

Fixed comments and a few preconditions

---

www/papers.html

Add the MegaLibm paper to our papers list. Onward and upward!

MegaLibm paper

---

src/sampling.rkt
src/timeline.rkt
src/web/resources/report-page.js
src/web/timeline.rkt
src/web/traceback.rkt

These are all over the place but don't affect any functionality, I think.

Minor cleanups to the HTML

---

src/timeline.rkt

This should make timeline-push! even faster.

Add a non-hash fast-path to `timeline-push!`, too

---

src/core/egg-herbie.rkt

This was lying around in a stash on my computer, let's merge it

Tiny cleanup in `egg-herbie`

---

.github/workflows/distribute.yml
.github/workflows/plugins.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.github/workflows/tools.yml
.github/workflows/unit-test.yml

This should remove most of the warnings about outdated actions.

Update CI actions

---

src/web/resources/report-page.js

This just cleans up some code and fixes some minor bugs.

Minor refactors to index page

---

src/config.rkt
src/core/localize.rkt
src/error-table.rkt
src/ground-truth.rkt
src/sampling.rkt
src/timeline.rkt
src/web/timeline.rkt

This PR improves some reporting code. I made these changes a while ago, in the process of trying to get longer Taylor series working.

Fix various unrelated bugs

---

src/ground-truth.rkt
src/mainloop.rkt
src/reprs/runtime/float32.rkt
src/web/timeline.rkt

- Reorganize `mainloop.rkt`
- Simpler output for `mix-sample`
- Make `bigfloat->float32` way faster

Minor tweaks

---

src/accelerator.rkt
src/load-plugin.rkt
src/platforms/AVX.rkt
src/reprs/binary32.rkt
src/reprs/binary64.rkt
src/syntax/read.rkt

Adds the AVX platform as well as the hack to run all benchmarks, even if they contain unimplemented operations.

AVX platform

---

src/syntax/read.rkt

Follow up PR from https://github.com/herbie-fp/herbie/pull/775. Added warnings for 0/1-ary cases of +, *, /. Switched to guarded evaluation.

Improved warnings for ARITHMETIC ops

---

infra/cost.rkt
infra/platforms/fpcore.py
infra/platforms/runner.py

Wrote Herbie result jsons from racket side and read into list on the python side

Varun10p platforms

---

www/doc.html

Adds Brett's latest blog post about Herbie as a numerical compiler to the blog post list.

Add Brett's blog post to the blog list

---

infra/baseline.sh

Bash Script for running baseline and getting results

Platforms baseline eval

---

infra/nightly.sh
infra/platforms-eval.py
infra/platforms-eval.sh
infra/platforms/baseline.py
infra/platforms/compare.py
infra/platforms/improve.py
infra/platforms/merge.py
infra/platforms/platforms/python.py
infra/platforms/platforms/runner.py
infra/platforms/platforms/runners.py
infra/platforms/plot.py
infra/platforms/server.rkt
infra/platforms/tune.py

This PR finishes #815 and integrates the baseline evaluation into the larger evaluation.

Platforms baseline eval (part 2)

---

plots.py
src/config.rkt
src/core/egg-herbie.rkt
src/core/localize.rkt
src/core/rr.rkt
src/herbie.rkt
src/mainloop.rkt
src/patch.rkt
src/preprocess.rkt

Option for naive cost model flag for experiments.
Current plot produced (UPDATED):

Old cost model option

---

infra/nightly.sh
infra/platforms-eval.py
infra/platforms-eval.sh
infra/platforms/baseline.py
infra/platforms/compare.py
infra/platforms/improve.py
infra/platforms/platforms/avx.py
infra/platforms/platforms/c.py
infra/platforms/platforms/cache.py
infra/platforms/platforms/math.py
infra/platforms/platforms/mkl.py
infra/platforms/platforms/python.py
infra/platforms/platforms/runner.py
infra/platforms/platforms/runners.py
infra/platforms/platforms/util.py
infra/platforms/plot.py
infra/platforms/run.py
infra/platforms/server.rkt
src/accelerator.rkt

Platforms eval can now be run on multiple seeds in parallel. Useful for cycle servers with large core counts.

Platforms eval with parallel seeds

---

Makefile

This package now exists and I've tested that installs on M1 Macs work great.

Handle the new `macosm1` package in the Makefile

---

src/herbie.rkt
src/multi-command-line.rkt

The PR is kind of ugly because of `multi-command-line` but it works and that's probably enough.

Add a flag to show the current version (fixes #630)

---

infra/testApi.mjs

This PR Fixes an incorrect use of the `improve-start` POST endpoint.

Fix improve-start API test

---

infra/testApi.mjs
src/web/demo.rkt

The goal of this PR is to introduce the idea of a Job to Herbie and unify the calling of the `improve`,`improve-start` and `sample` endpoints through this new API.
This also builds off #844 
This is not a finished Job abstraction but tries to lay out the general shape of what a job abstraction might be.

Herbie Job abstraction

---

src/web/common.rkt
src/web/resources/report-page.js
src/web/resources/report.css
src/web/timeline.rkt

This PR cleans up `timeline.rkt` and does a lot of substantial refactors to `report-page.js`

Fix various minor bugs and annoyances on the generated HTML

---

src/info.rkt

Depend on Rival 2.0

---

www/doc/2.1/api-endpoints.html
www/doc/2.1/release-notes.html

Fixes small nit pick on the title tag.

2.1 instead of 2.0

---

.gitignore
infra/survey/.gitignore
infra/survey/README.md
infra/survey/seed-variance.sh
infra/survey/src/plot-results.sh
infra/survey/src/seed-bar-chart.py
infra/survey/src/seed-violin-plot.py
infra/survey/src/test-versus-plot.py
infra/survey/src/test-violin-plot.py

This PR adapts Zach's Herbie seed [survey](https://github.com/ztatlock/herbie-stats/blob/main/seed-variance.sh). The code is under `infra/survey`.

Adds Zach's seed survey

---

www/doc/2.1/release-notes.html

This PR adds a brief note on the new Odyssey release to the Herbie 2.1 release notes.
Extended Odyssey release notes:
* Recently we added support for running FPTaylor on expressions shown in the [Odyssey interface](https://herbie-fp.github.io/odyssey/) for Herbie. Expressions can be analyzed by selecting "FPTaylor Analysis" from the tool dropdown for an expression. This is a part of a larger effort to combine different floating point tools as parts of an analysis.
* Odyssey now supports exporting expressions to different languages using the new "Expression Export" tool.
* Herbie has been updated with an HTTP API endpoint to support Odyssey's expression export. Herbie's HTTP API endpoints are documented [here](https://herbie.uwplse.org/doc/latest/api-endpoints.html).
* Like the Herbie …

Add brief Odyssey release notes.

---

src/web/history.rkt

With #875, proof steps may involved mixed real/float expressions. The quick solution in this PR simply renders the expressions in math and displays error estimates only when possible. A side effect of this approach is some steps show an "operator selection" step where the math does not change.

Handle mixed real/float expression proofs

---

src/platforms/default.rkt

Changes some of the default cost model values to be a little more reasonable. Upside is Herbie's output is less wonky / more believable and looks closer to expressions before #875.

Tweak cost model

---

www/doc/2.1/api-endpoints.html

This PR Resolves the comments from PR #900 as it was merged without these changes.

Resolve comments from #900

---

src/web/demo.rkt

This seems to have been lost at some point.

Fix the `--quiet` flag to actually be quiet

---

src/web/demo.rkt

This PR is an alternative to #898 that makes a much smaller change to the code.

Fix the `--save-session` code by allowing generate-page to be called once

---

Dockerfile
www/doc/2.1/docker.html

I haven't had this successfully run yet, but it's at least better... Waiting for help, I think there are issues due to me using an arm64 mac.

Various edits to the Docker file suggested by Docker

---

src/core/sampling.rkt

This unit test was commented out for some reason, but it's still good.

Re-enable an old test

---

src/core/test-rules.rkt

This PR updates two of the blocks in `test-rules.rkt` to use real rules, not impl rules. In reality it basically uses double precision. The last block in `test-rules.rkt` checks FP-safe rules, and I think the long term plan there is that these should be impl rules from the very start, but I'll leave that for later clean-up.

Use real rules, not impl rules, for testing correctness / soundness

---

src/main.rkt

Fixes silly mistakes from rebasing.

Fix rebase error with --no-browser.

---

src/api/demo.rkt
src/api/server.rkt
src/reports/plot.rkt

This PR undoes some of the changes introduced in #977  that were prematurely merged before proper review.

Undoing bad changes.

---

src/syntax/syntax-check.rkt
src/syntax/type-check.rkt

I think in some of our refactors these stopped working.

Fix programs with casts and `!` annotations

---

src/api/server.rkt

This PR fixes a subtle "bug" to prevent multiple workers from working on the same job. This bug arises when a worker begins working on a job and then multiple copies of that same job are submitted in the window that the worker is working on that job. This does produce bad results but does allow the server to get backed up by doing duplicate work for the length that the first job takes.

Prevent workers from doing duplicate work.

---

bench/graphics/lod.fpcore

Adds two more benchmarks to the graphics set of benchmarks thanks to @benwang33 and Bill Zorn.

Add two more benchmarks to lod.

---

src/reports/resources/report-page.js

This PR mostly changes `update()` to a nullary function that just reads and writes the globals directly; I think it's a little simpler and in practice all the data passed in was already the same as those globals.

Minor reorganizations / cleanups to report page

---

src/api/server.rkt

This fixes one bug in the new server. Noticed in issue #1006.

Fix bug in server assigning work.

---

www/papers.html

Arxiv version to the paper of Herbie's real evaluation kernel has been added

Papers list update

---

src/api/server.rkt

Surface total jobs in the server not just the number of jobs being worked on.

Better job count.

---

src/api/demo.rkt
src/api/server.rkt

This PR reduces code paths into the server through a `manager-ask` helper function. This PR will make future improvements to the server like a `no-place-mode` easier to implement as it is now easier to branch on whether a manager (place mode) is to be used.

Server Improvements: manager-ask

---

src/core/localize.rkt

This PR makes `localize.rkt` quite a bit shorter and easier to read, and also gives us the opportunity to comment / describe some of what's going on by adding nice abstraction boundaries.

Add helper functions `local-error` and `remove-infinities` to `localize.rkt`

---

src/core/egglog-herbie.rkt
src/platforms/bool.rkt
src/platforms/default.rkt
src/platforms/libm.rkt
src/platforms/math.rkt

Cleaned up excess nodes. Using :unextractable to ban lift from extraction.

Varun10p egglog

---

src/core/egg-herbie.rkt
src/core/localize.rkt
src/core/mainloop.rkt
src/core/patch.rkt
src/core/preprocess.rkt
src/core/programs.rkt
src/core/reduce.rkt
src/core/rules.rkt
src/core/test-rules.rkt
src/plugin.rkt
src/reports/resources/report-page.js
src/reports/traceback.rkt
src/syntax/platform.rkt

- Delete dead code in `traceback.rkt`
- Replace `getMinimum` with JS cleverness
- Drop `spec-has-nan?` and supporting code
- No rulesets, just rules

Random Cleanup

---

.github/workflows/resyntax-autofixer.yml

Allow Resyntax to make more fixes at a time

---

src/reports/timeline.rkt

This PR adds the total memory allocated for the timeline.

Display the total memory allocated in timeline.

---

src/api/server.rkt

This PR allows turning on and off all server console output to not pollute the console when output is not needed.
This is to help make #1064 use of the job server to retain its current output during nightly runs.  
A possible next step would be to use something like [Racket Logger ](https://docs.racket-lang.org/reference/logging.html) for both nightly output and server output.

Allow turning on and off logging when starting job server.

---

src/api/server.rkt

This PR restores support for using `--threads yes`.

Support passing yes for thread count.

---

src/api/server.rkt

This PR sets the default logging to false which was missed by the previous [PR](https://github.com/herbie-fp/herbie/pull/1063).

Default logging to false

---

egg-herbie/Cargo.lock
egg-herbie/Cargo.toml

This PR updates the pinned egg version to an egg version that fixes an egg proof bug we found.

Update egg version to fix #1084

---

egg-herbie/src/math.rs

This PR is half of #1109—just the cap on `pow` constant-fold exponents—because I expect this to be an easy merge and also because it's getting in the way of experiments I want to do.

Just the max abs exponent portion of #1109

---

src/core/programs.rkt
src/reports/history.rkt
src/syntax/matcher.rkt

`raco fmt` was updated, this PR updates our code to match.

Update indentation of `let/ec` with `raco fmt` update

---

src/api/server.rkt
src/core/egg-herbie.rkt
src/core/patch.rkt
src/core/programs.rkt
src/core/simplify.rkt
src/plugin.rkt
src/reports/history.rkt
src/syntax/matcher.rkt
src/syntax/syntax.rkt

More simplifications: remove unused parts of the syntax.rkt API and hard-code extractor in egg-Herbie.rkt

Simplify more stuff

---

src/core/rival.rkt

This PR helps merging Rival's PR on hints safely without breaking any contracts and fails on nightly.
After this branch is merged to main - Rival can also be merged.

Preparation for rival's hint merge

---

src/core/programs.rkt
src/reports/history.rkt
src/reports/resources/report.html

Derivations were broken as a result of some changes, this PR fixes it.
I also accidentally pushed a fix to an annoying "white page" error to this branch, woops.

Fix derivation reports

---

www/doc/2.2/input.html

Tweak to docs suggested by Ganesh

---

src/info.rkt
src/reports/common.rkt

added cuda to define language block

Enable CUDA output in Herbie

---

src/info.rkt
src/reports/common.rkt

Reverts herbie-fp/herbie#1158. It was broken.

Revert "Enable CUDA output in Herbie"

---

www/papers.html

This PR adds the ExplaniFloat paper to www/papers.html.

Add ExplaniFloat to www/papers.html

---

src/core/alt-table.rkt
src/core/batch.rkt
src/core/bsearch.rkt
src/core/compiler.rkt
src/core/egg-herbie.rkt
src/core/explain.rkt
src/core/localize.rkt
src/core/mainloop.rkt
src/core/patch.rkt
src/core/points.rkt
src/core/preprocess.rkt
src/core/programs.rkt
src/core/reduce.rkt
src/core/regimes.rkt
src/core/rival.rkt
src/core/rules.rkt
src/core/sampling.rkt
src/core/searchreals.rkt
src/core/simplify.rkt
src/core/taylor.rkt
src/core/test-rules.rkt
src/syntax/platform.rkt

These functions are all also unused thanks to #1167. While here I also cleaned up imports in `src/core`

Remove more unused functions

---

egg-herbie/main.rkt
egg-herbie/src/lib.rs
egg-herbie/src/math.rs
src/core/egg-herbie.rkt

This is also enabled by #1167 and #1168.

We now always constant-fold when doing egraphs

---

src/api/server.rkt
src/utils/errors.rkt

This is to help the Odyssey team surface warnings during sampling.

Add `warnings`, `name`, `time`, and `status` to every API message

---

src/api/sandbox.rkt
src/core/egglog-herbie.rkt

Not a big deal but worth fixing.

Fix `fmt` on `main`, the resyntax thing broke it

---

src/api/sandbox.rkt
src/api/server.rkt
src/core/bsearch.rkt
src/core/compiler.rkt
src/core/egglog-herbie.rkt
src/core/explain.rkt
src/core/localize.rkt
src/core/points.rkt
src/core/preprocess.rkt
src/core/regimes.rkt
src/core/rival.rkt
src/core/sampling.rkt
src/core/searchreals.rkt
src/core/test-rules.rkt
src/syntax/syntax.rkt
src/utils/common.rkt

This PR changes our representation of points to use a vector instead of a list. This is bizarrely low-level, but it might speed up sampling, which would be a win since it's a pretty large fraction of runtime, though I doubt it would help _that_ much.

Vector points

---

src/reports/resources/report-page.js

This PR just continues the long journey of deleting duplicate or bad code from `report-page.js`.

Refactor `report-page.js`

---

src/core/batch.rkt

This PR rewrites the tree-size function to handle size-zero batches, which somehow happen.

Rewrite and fix tree-size function

---

src/api/demo.rkt
src/api/server.rkt
src/core/points.rkt

This PR just deletes / inlines a bit more code in the server.

More cleanups in `server.rkt`

---

src/core/mainloop.rkt

This just renames a few functions.

Clean up `mainloop` a tiny bit

---

AGENT.md

At least I now know it's using it!

Woops! Wrong things in `AGENT.md`

---

src/syntax/syntax.rkt

Delete an unused function

---

src/core/rules.rkt

This PR just deletes a bunch of unsound rules. They don't seem super valuable (no impact on nightlies) and fewer unsound rules is just less to think about.

Delete some unsound rules that don't seem to be used

---

bench/demo.fpcore

This PR adds part of the discriminant of a cubic equation, repeated multiplication from x - 1 to x - 20 ([x -1] * [x - 2] * [x - 3] * … * [x - 19] * [x - 20]), and the law of cosines [sqrt(pow(a, 2) + pow(b, 2) - 2 * a * b * cos(C))] as benchmarks. (you can move or rename the file)
#1292

New benchmarks (new PR)

---

src/api/server.rkt
src/config.rkt
src/core/regimes.rkt
src/main.rkt
src/reports/make-graph.rkt
www/doc.html
www/doc/2.2/input.html
www/doc/2.2/options.html
www/doc/2.2/platforms.html

This PR also cleans up `input.html` and `options.html`, which are linked from `platforms.html`.

Write documentation on adding a platform

---

src/core/mainloop.rkt

Pretty simple, found by @LooneyLiberator

Check that there's an implementation of `if` before we do regimes

---

src/api/server.rkt
src/core/egg-herbie.rkt
src/core/searchreals.rkt

This PR fixes #1284 and also [another error from the demo](https://herbie.uwplse.org/demo/9ca0fd5c4bbfe3e19cd9950dabecddda51b5dd17.1a83c9f5186db102b678a2d5f869f99992469071/graph.html). Both are kinda subtle but it's good to clear these out before release.

Fix some random bugs

---

src/core/rival.rkt
src/reports/timeline.rkt
src/utils/timeline.rkt

Relies on https://github.com/herbie-fp/rival/pull/120 to be merged.

Include rival memory profile in report
